(()=>{
'use strict';
const D=window.GuMudData,E=window.GuMudEngine,P=window.GuMudPortraits,KEY='gu_mud_v1_auto';
const $=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('zh-CN',{maximumFractionDigits:1});
let s=null,side='aperture',toastTimer;
function toast(t){const n=$('toast');if(!n)return;n.textContent=t;n.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove('show'),3600)}
function loadAuto(){try{const raw=localStorage.getItem(KEY);return raw?E.load(raw):null}catch{return null}}
function saveAuto(){if(!s)return;try{localStorage.setItem(KEY,E.save(s))}catch{toast('浏览器无法写入本地存档，请导出 JSON。')}}
function meter(label,v,max,cls=''){const p=Math.max(0,Math.min(100,Number(v)/Math.max(1,Number(max))*100));return `<div class="meter"><div class="meter-line"><span>${esc(label)}</span><span>${fmt(v)} / ${fmt(max)}</span></div><div class="track ${cls}"><i style="width:${p}%"></i></div></div>`}
function header(){const p=s.p,l=D.LOCATIONS[s.loc];return `<header class="mud-header"><div class="brand"><div class="seal">蛊</div><div><h1>蛊真人 · MUD</h1><small>CHOICE-DRIVEN CULTIVATION WORLD</small></div></div><div class="top-status"><span>第 <b>${E.day(s)}</b> 日</span><span>${esc(l.region)}</span><span>${esc(E.realm(s))}</span><span>${p.rank>=6?'仙元石':'元石'} <b>${fmt(p.rank>=6?p.immortal:p.stones)}</b></span></div><div class="top-actions"><button data-ui="save">导出存档</button><button data-ui="new">新局</button><a href="legacy.html">旧版</a></div></header>`}
function playerPanel(){const p=s.p,d=E.derived(s),eq=Object.values(s.equip).filter(Boolean).map(id=>D.EQUIPMENT[id]?.name).filter(Boolean).join(' · ');return `<aside class="panel player-panel"><div class="player-art"><img src="assets/portraits/player.svg" alt="玩家立绘"></div><div class="player-info"><div class="eyebrow">${esc(p.aperture.grade)}空窍 · ${esc(D.RANKS[p.rank].essence)}</div><h2>${esc(p.name)}</h2><div class="realm">${esc(E.realm(s))}</div><div class="meters">${meter('身体',p.hp,100,p.hp<35?'bad':'')}${meter(p.rank>=6?'仙元':'真元',p.aperture.essence,E.essenceMax(s),'gold')}${meter('修为',p.progress,D.RANKS[p.rank].threshold,'gold')}${meter('空窍稳定',p.aperture.stability,100)}</div><div class="stat-grid"><div><span>攻击</span><b>${fmt(d.attack)}</b></div><div><span>防御</span><b>${fmt(d.defense)}</b></div><div><span>领悟</span><b>${fmt(p.insight)}</b></div><div><span>恶名</span><b>${fmt(p.infamy)}</b></div></div><p class="small muted">装备：${esc(eq||'无')}</p></div></aside>`}
function sceneClass(mode){return mode==='battle'?'mode-battle':mode==='dungeon'?'mode-dungeon':mode==='ending'?'mode-ending':''}
function portrait(speaker){return speaker&&P?P.render(speaker):''}
function stage(){const ctx=E.context(s),l=D.LOCATIONS[s.loc],cs=E.choices(s);const eyebrow=ctx.mode==='event'?'系统事件 · 你的选择会进入后续状态':ctx.mode==='battle'?'交锋 · 每个选项结算一回合':ctx.mode==='dungeon'?'副本 · 风险与奖励同时累积':ctx.mode==='ending'?'本局结局':'系统根据当前位置与状态提供合法行动';return `<main class="panel stage"><section class="scene ${sceneClass(ctx.mode)}"><div class="scene-label"><div class="eyebrow">${esc(l.region)} · ${esc(ctx.mode.toUpperCase())}</div><h2>${esc(ctx.title)}</h2><p>${esc(l.desc)}</p></div>${portrait(ctx.speaker)}</section><section class="story"><div class="eyebrow">${eyebrow}</div><h2>${esc(ctx.title)}</h2><p>${esc(ctx.text)}</p></section><section class="choices">${cs.map((c,i)=>`<button class="choice" data-choice="${i}" ${c.disabled?'disabled':''}><span class="num">${String(i+1).padStart(2,'0')}</span><span><strong>${esc(c.label)}</strong><small>${esc(c.desc||'')}</small>${c.disabled?`<em>${esc(c.disabled)}</em>`:''}</span></button>`).join('')}</section></main>`}
const tabNames={aperture:'空窍',gu:'蛊虫',equipment:'装备',moves:'杀招',dungeons:'副本',blessed:'福地',achievements:'成就',relations:'人物'};
const pathName=id=>D.PATHS.find(x=>x.id===id)?.name||id;
function aperturePanel(){const p=s.p,marks=Object.entries(p.aperture.marks||{}).map(([k,v])=>`${pathName(k)} ${fmt(v)}`).join('、')||'尚无明显道痕';return `<h3>空窍系统</h3><div class="line"><span>资质</span><span>${p.aperture.grade} ${p.aperture.aptitude}%</span></div><div class="line"><span>境界</span><span>${E.realm(s)}</span></div><div class="line"><span>${p.rank>=6?'仙元':'元海'}</span><span>${fmt(p.aperture.essence)} / ${fmt(E.essenceMax(s))}</span></div><div class="line"><span>空窍稳定</span><span>${fmt(p.aperture.stability)}</span></div><div class="line"><span>主修</span><span>${pathName('light')}</span></div><div class="card"><h4>道痕</h4><p>${esc(marks)}</p></div><div class="card"><h4>基础属性</h4>${Object.entries(p.stats).map(([k,v])=>`<div class="line"><span>${esc(k)}</span><span>${fmt(v)}</span></div>`).join('')}</div>`}
function guPanel(){return `<h3>蛊虫 / 仙蛊</h3>${s.gu.map(g=>{const d=D.GU[g.id];return `<div class="card"><h4>${esc(d.name)} ${g.uid===s.vital?'<span class="badge gold">本命蛊</span>':''} ${d.kind==='immortal'?'<span class="badge gold">仙蛊</span>':''}</h4><p>${d.rank} 转 · ${pathName(d.path)} · ${esc(d.desc)}</p><div class="line"><span>炼化</span><span>${g.refined?'已炼化':fmt(g.refine)+'%'}</span></div><div class="line"><span>生机 / 饥饿</span><span>${fmt(g.hp)} / ${fmt(g.hunger)}</span></div><div class="line"><span>羁绊</span><span>${fmt(g.bond)}</span></div></div>`}).join('')||'<p class="muted">没有蛊虫。</p>'}<h3>蛊材</h3>${Object.entries(s.mat).filter(([,n])=>n>0).map(([id,n])=>`<div class="line"><span>${esc(D.MATERIALS[id].name)}</span><span>${fmt(n)}</span></div>`).join('')||'<p class="muted">暂无材料。</p>'}`}
function equipmentPanel(){const slots={robe:'衣袍',bracer:'护腕',boots:'靴',token:'信物',pouch:'行囊'};return `<h3>装备系统</h3>${Object.entries(slots).map(([slot,name])=>`<div class="line"><span>${name}</span><span>${s.equip[slot]?esc(D.EQUIPMENT[s.equip[slot]]?.name):'空'}</span></div>`).join('')}<h3>持有装备</h3>${s.bagEq.map(id=>{const d=D.EQUIPMENT[id];return `<div class="card"><h4>${esc(d.name)} <span class="badge">${d.rank} 转</span></h4><p>${esc(d.desc)}</p></div>`}).join('')||'<p class="muted">没有备用装备。</p>'}`}
function movesPanel(){return `<h3>杀招系统</h3>${s.moves.length?s.moves.map(id=>{const m=D.KILLER_MOVES[id];return `<div class="card"><h4>${esc(m.name)} ${m.kind==='immortal'?'<span class="badge gold">仙道</span>':''}</h4><p>${m.rank} 转 · ${pathName(m.path)} · ${esc(m.desc)}</p></div>`}).join(''):'<p class="muted">满足核心蛊虫、境界和领悟要求后，主选项会出现“推演杀招”。</p>'}<h3>已知融合路线</h3>${s.fusions.map(id=>{const f=D.FUSIONS[id];return `<div class="card"><h4>${esc(D.GU[f.result].name)}</h4><p>${esc(f.desc)}</p></div>`}).join('')}`}
function dungeonPanel(){return `<h3>副本</h3>${Object.values(D.DUNGEONS).map(d=>`<div class="card"><h4>${esc(d.name)} ${s.cleared.includes(d.id)?'<span class="badge gold">已通关</span>':s.openDungeons.includes(d.id)?'<span class="badge">已发现</span>':''}</h4><p>${d.minRank}-${d.maxRank} 转 · ${esc(D.LOCATIONS[d.location].name)}<br>${esc(d.desc)}</p></div>`).join('')}`}
function blessedPanel(){const b=s.land;if(!b)return `<h3>福地</h3><p class="muted">六转飞升时仙窍升格为可经营福地。资源点、仙元池、阵法和灾劫将在这里出现。</p>`;return `<h3>${esc(b.name)}</h3><div class="line"><span>稳定</span><span>${fmt(b.stability)}</span></div><div class="line"><span>资源点</span><span>${fmt(b.nodes)}</span></div><div class="line"><span>仙元池</span><span>${fmt(b.pool)}</span></div><div class="line"><span>阵法</span><span>${fmt(b.formation)}</span></div><div class="line"><span>人口</span><span>${fmt(b.population)}</span></div><div class="line"><span>距下次灾劫</span><span>${Math.max(0,fmt(b.trib))} 日</span></div>`}
function achievementsPanel(){return `<h3>成就 ${s.ach.length}/${Object.keys(D.ACHIEVEMENTS).length}</h3>${Object.values(D.ACHIEVEMENTS).map(a=>`<div class="card" style="opacity:${s.ach.includes(a.id)?1:.35}"><h4>${s.ach.includes(a.id)?'◇':'·'} ${esc(a.name)}</h4><p>${esc(a.desc)}</p></div>`).join('')}`}
function relationsPanel(){const names={fangzheng:'古月方正',mobei:'古月漠北',fangyuan:'古月方源',elder:'古月师',jiangya:'江牙',jiafu:'贾富'};return `<h3>人物关系</h3>${Object.entries(s.rel).map(([id,v])=>`<div class="card"><h4>${esc(names[id]||id)}</h4><div class="line"><span>关系</span><span>${fmt(v)}</span></div><div class="line"><span>人情</span><span>${fmt(s.favor[id]||0)}</span></div></div>`).join('')}`}
function sidePanel(){const fn={aperture:aperturePanel,gu:guPanel,equipment:equipmentPanel,moves:movesPanel,dungeons:dungeonPanel,blessed:blessedPanel,achievements:achievementsPanel,relations:relationsPanel}[side];return `<aside class="panel side"><nav class="side-tabs">${Object.entries(tabNames).map(([id,n])=>`<button data-side="${id}" class="${side===id?'active':''}">${n}</button>`).join('')}</nav><div class="side-body">${fn()}</div></aside>`}
function logBox(){return `<section class="panel logbox"><h3>行路记录</h3>${s.log.slice(0,18).map(l=>`<div class="logrow ${esc(l.kind)}"><b>第${Math.floor(l.time/24)+1}日</b>${esc(l.text)}</div>`).join('')}</section>`}
function intro(){const has=!!loadAuto();return `<div class="modal"><div class="modal-card intro"><div class="intro-copy"><div class="eyebrow">南疆 · 青茅山 · 古月山寨</div><h2>从开窍开始</h2><p>这是一个系统提供选项、玩家负责选择的 MUD。你的决定会改变人物关系、资源、蛊虫、装备、修为、副本开放与最终结局。</p><form id="new-form" class="form"><label>姓名<input name="name" value="古月族人" maxlength="20"></label><label>资质<select name="grade"><option>甲等</option><option>乙等</option><option selected>丙等</option><option>丁等</option></select></label><label class="full">世界种子<input name="seed" value="青茅山-MUD" maxlength="80"></label><button class="primary full" type="submit">开窍入世</button>${has?'<button class="full" type="button" data-ui="continue">继续上次存档</button>':''}</form><p class="small muted">1–9 转完整成长；六转开启福地和仙元；后期开放仙蛊、仙道杀招和多结局。</p></div><div class="intro-art"><img src="assets/portraits/player.svg" alt="玩家立绘"></div></div></div>`}
function render(){if(!s){$('root').innerHTML=intro();return}$('root').innerHTML=`<div class="mud-shell">${header()}<div class="layout">${playerPanel()}${stage()}${sidePanel()}</div>${logBox()}<footer class="footer">MUD v1 · 1–9 转 / 空窍 / 仙蛊 / 福地 / 装备 / 融合 / 仙道杀招 / 副本 / 多结局</footer></div>`}
function exportSave(){const blob=new Blob([E.save(s)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`gu-mud-${s.p.name}-day${E.day(s)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出 JSON 存档。')}
function doCommand(cmd){if(cmd.type==='ui'&&cmd.id==='new'){if(confirm('确定开始新局？当前自动存档会被替换。')){s=null;localStorage.removeItem(KEY);render()}return}const r=E.dispatch(s,cmd);if(!r.ok){toast(r.message);return}saveAuto();render()}
document.addEventListener('submit',e=>{if(e.target.id!=='new-form')return;e.preventDefault();const f=new FormData(e.target);s=E.newGame({name:f.get('name'),grade:f.get('grade'),seed:f.get('seed')});saveAuto();render()});
document.addEventListener('click',e=>{const c=e.target.closest('[data-choice]');if(c&&!c.disabled){const choice=E.choices(s)[Number(c.dataset.choice)];if(choice)doCommand(choice.cmd);return}const st=e.target.closest('[data-side]');if(st){side=st.dataset.side;render();return}const ui=e.target.closest('[data-ui]');if(ui){if(ui.dataset.ui==='continue'){s=loadAuto();render()}else if(ui.dataset.ui==='save')exportSave();else if(ui.dataset.ui==='new')doCommand({type:'ui',id:'new'});}});
document.addEventListener('keydown',e=>{if(!s||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;const n=Number(e.key);if(n>=1&&n<=9){const choice=E.choices(s)[n-1];if(choice&&!choice.disabled)doCommand(choice.cmd)}});
s=loadAuto();render();
})();