(function(root,factory){const E=factory(typeof module==='object'&&module.exports?require('./data.js'):root.GuMudData);if(typeof module==='object'&&module.exports)module.exports=E;else root.GuMudEngine=E;})(globalThis,D=>{
'use strict';
const C=(x,a,b)=>Math.max(a,Math.min(b,x)), cp=x=>JSON.parse(JSON.stringify(x)), ev=Object.fromEntries(D.EVENTS.map(x=>[x.id,x]));
const err=m=>{throw Error(m)};
function hash(x){let h=2166136261;for(const c of String(x)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0||1}
function rng(s){let x=s.rng>>>0;x^=x<<13;x^=x>>>17;x^=x<<5;s.rng=x>>>0||1;return s.rng/4294967296}
const roll=(s,p)=>rng(s)<C(p,0,1), day=s=>Math.floor(s.time/24)+1;
function note(s,text,kind='story'){s.log.unshift({time:s.time,text,kind});if(s.log.length>140)s.log.length=140}
function realm(s){return `${D.RANKS[s.p.rank].name} · ${D.STAGES[s.p.stage]}`}
function essenceMax(s){return s.p.rank>=6?8+(s.p.rank-6)*6+(s.land?.pool||0):Math.round(s.p.aperture.aptitude*(1+(s.p.rank-1)*.42+s.p.stage*.08))}
function eqStats(s){const z={def:0,str:0,agi:0,amp:0};for(const id of Object.values(s.equip)){const q=D.EQUIPMENT[id]?.stats||{};z.def+=q.defense||0;z.str+=q.strength||0;z.agi+=q.agility||0;z.amp+=q.daoAmplify||0}return z}
const hasGu=(s,id)=>s.gu.some(g=>g.id===id&&g.refined&&g.hp>0), mat=(s,id)=>s.mat[id]||0;
function mats(s,o){for(const[k,v]of Object.entries(o||{}))if(D.MATERIALS[k])s.mat[k]=Math.max(0,(s.mat[k]||0)+v)}
function ach(s,id){if(D.ACHIEVEMENTS[id]&&!s.ach.includes(id)){s.ach.push(id);note(s,`成就「${D.ACHIEVEMENTS[id].name}」`,'achievement')}}
function addGu(s,id,refined=false){const d=D.GU[id];if(!d)err('未知蛊虫');const g={uid:`g${s.next++}`,id,rank:d.rank,refined,refine:refined?100:0,hunger:0,hp:100,bond:refined?20:0};s.gu.push(g);if(refined&&!s.vital){s.vital=g.uid;ach(s,'firstGu')}if(d.kind==='immortal')ach(s,'immortalGu');return g}
function newGame({name='古月族人',grade='丙等',seed='青茅山'}={}){if(!D.GRADES[grade])err('无效资质');const a=D.GRADES[grade].aptitude,s={version:D.VERSION,rng:hash(seed),seed:String(seed),next:1,time:6,alive:true,loc:'school',visited:['school'],openLoc:['school','village','guRoom','dorm','inn','bamboo','river'],p:{name:String(name).slice(0,20),rank:1,stage:0,progress:0,hp:100,stamina:100,spirit:75,stones:6,immortal:0,rep:0,infamy:0,suspicion:0,insight:8,clue:0,secrecy:50,stats:{strength:12,agility:12,will:14,comprehension:14,refinement:12,luck:10},aperture:{grade,aptitude:a,essence:a,stability:78,marks:{light:0}}},mat:Object.fromEntries(Object.keys(D.MATERIALS).map(k=>[k,0])),equip:{robe:'bambooRobe',bracer:null,boots:null,token:'clanToken',pouch:null},bagEq:['beastBracer','roadBoots'],gu:[],vital:null,fusions:['moonGlow'],moves:[],rel:{fangzheng:0,mobei:0,fangyuan:0,elder:0,jiangya:0,jiafu:0},favor:{},flags:{},seen:[],event:'opening',battle:null,dungeon:null,openDungeons:[],cleared:[],land:null,ach:[],ending:null,log:[]};mats(s,{food:8,water:8,petal:18,wine:1,ore:3,bone:2});addGu(s,'moon');note(s,'希望蛊散去，你从古月山寨开始。','major');return s}
function normal(s){const p=s.p;p.rank=C(p.rank,1,9);p.stage=C(p.stage,0,3);p.progress=C(p.progress,0,D.RANKS[p.rank].threshold);for(const k of ['hp','stamina','spirit','suspicion','infamy','clue','secrecy'])p[k]=C(p[k],0,100);p.rep=C(p.rep,-100,100);p.aperture.stability=C(p.aperture.stability,0,100);p.aperture.essence=C(p.aperture.essence,0,essenceMax(s));p.stones=Math.max(0,p.stones);p.immortal=Math.max(0,p.immortal);for(const g of s.gu){g.refine=C(g.refine,0,100);g.hunger=C(g.hunger,0,100);g.hp=C(g.hp,0,100);g.bond=C(g.bond,0,100)}if(p.hp<=0){s.alive=false;s.event=s.battle=s.dungeon=null}}
function eventReady(s,e){const c=e.condition||{};return!s.seen.includes(e.id)&&s.event!==e.id&&(!e.afterDay||day(s)>=e.afterDay)&&(!e.location||s.loc===e.location)&&(!c.rank||s.p.rank>=c.rank)&&(c.stage===undefined||s.p.stage>=c.stage)&&(!c.clue||s.p.clue>=c.clue)}
function pump(s){if(!s.alive||s.event||s.battle||s.dungeon||s.ending)return;for(const e of D.EVENTS)if(eventReady(s,e)){s.event=e.id;break}}
function advance(s,h){for(let i=0;i<h&&s.alive;i++){s.time++;s.p.aperture.essence+=s.p.rank<6?s.p.aperture.aptitude/18:.18+(s.land?.pool||0)*.03;s.p.stamina+=1.5;s.p.spirit+=.8;for(const g of s.gu){g.hunger+=g.rank>=6?.25:.7;if(g.hunger>=100){g.hp-=1;if(g.uid===s.vital&&g.hp<=0)s.p.hp-=30}}if(s.land){s.land.trib-=1/24;if(s.time-s.land.last>=24){mats(s,{immortalMaterial:Math.floor(s.land.nodes/2),food:s.land.nodes*2});s.p.immortal+=Math.floor(s.land.pool/2);s.land.last=s.time}if(s.land.trib<=0&&!s.battle)startBattle(s,'tribulation')}}normal(s);pump(s);check(s)}
function effects(s,f={}){const p=s.p;p.stones+=f.stones||0;p.immortal+=f.immortalStones||0;p.rep+=f.rep||0;p.infamy+=f.infamy||0;p.suspicion+=f.suspicion||0;p.insight+=f.insight||0;p.clue+=f.clue||0;p.secrecy+=f.secrecy||0;p.aperture.stability+=f.apertureStability||0;mats(s,f.materials);for(const[k,v]of Object.entries(f.relation||{}))s.rel[k]=(s.rel[k]||0)+v;for(const[k,v]of Object.entries(f.favor||{}))s.favor[k]=(s.favor[k]||0)+v;if(f.flag)s.flags[f.flag[0]]=f.flag[1];if(f.unlockDungeon&&!s.openDungeons.includes(f.unlockDungeon))s.openDungeons.push(f.unlockDungeon);if(f.unlockLocation&&!s.openLoc.includes(f.unlockLocation))s.openLoc.push(f.unlockLocation)}
function chooseEvent(s,id){const e=ev[s.event],c=e?.choices.find(x=>x.id===id);if(!c)err('无效事件选项');if(c.requiresGu&&!hasGu(s,c.requiresGu))err(`需要${D.GU[c.requiresGu].name}`);s.seen.push(e.id);s.event=null;if(c.ending){finish(s,c.ending);return}effects(s,c.effects);note(s,`${e.title}：${c.label}`,'choice');advance(s,1)}
function derived(s){const e=eqStats(s),gp=s.gu.filter(g=>g.refined&&g.hp>0).reduce((n,g)=>n+D.GU[g.id].power*(.5+g.bond/200),0),mp=Math.max(0,...s.moves.map(i=>D.KILLER_MOVES[i]?.power||0));return{attack:8+s.p.rank*9+(s.p.stats.strength+e.str)*1.2+gp*.45+mp*.25,defense:5+s.p.rank*6+e.def+s.p.stats.will*.35,agility:s.p.stats.agility+e.agi,amp:e.amp,breakChance:breakChance(s)}}
function breakChance(s){const p=s.p;return C(.46+p.aperture.aptitude*.003+p.stats.will*.003+p.aperture.stability*.0015-(p.rank-1)*.045-(100-p.spirit)*.0015,.12,.94)}
function reason(s,id){if(s.event)return'先处理事件';if(s.battle)return'战斗中';if(s.dungeon)return'副本中';if(!s.alive)return'角色已死亡';if(id==='cultivate'&&s.p.aperture.essence<Math.max(8,essenceMax(s)*.18))return'真元不足';if(id==='breakthrough'&&s.p.progress<D.RANKS[s.p.rank].threshold)return'修为未满';if(id==='breakthrough'&&s.p.rank===9&&s.p.stage===3)return'已到九转巅峰';if(id==='breakthrough'&&s.p.rank===5&&s.p.stage===3&&(mat(s,'immortalMaterial')<5||mat(s,'formation')<3))return'飞升需要5仙材与3阵材';return''}
function cultivate(s){const x=reason(s,'cultivate');if(x)err(x);s.p.aperture.essence-=Math.max(8,essenceMax(s)*.18);s.p.progress+=Math.max(5,(8+s.p.stats.comprehension*.32+s.p.aperture.aptitude*.08)*s.p.spirit/100);s.p.stamina-=10;s.p.spirit-=5;note(s,'温养空窍，修为增长。','action');advance(s,2)}
function makeLand(s){if(s.land)return;s.land={name:`${s.p.name}福地`,stability:68,pool:1,nodes:1,formation:0,population:8,trib:60,last:s.time};ach(s,'blessedLand')}
function breakthrough(s){const x=reason(s,'breakthrough');if(x)err(x);if(s.p.rank>=6){const n=Math.max(1,s.p.rank-5);if(s.p.immortal<n)err('仙元石不足');s.p.immortal-=n}if(s.p.rank===5&&s.p.stage===3)mats(s,{immortalMaterial:-5,formation:-3});if(roll(s,breakChance(s))){s.p.progress=0;if(s.p.stage<3)s.p.stage++;else if(s.p.rank<9){s.p.stage=0;s.p.rank++;s.p.aperture.marks.light=(s.p.aperture.marks.light||0)+s.p.rank*3;if(s.p.rank===6){makeLand(s);s.p.immortal+=2;ach(s,'immortal');for(const i of ['immortalAuction','tribulationField'])if(!s.openLoc.includes(i))s.openLoc.push(i);if(!s.openDungeons.includes('landSpirit'))s.openDungeons.push('landSpirit')}if(s.p.rank===8&&!s.openDungeons.includes('venerableRoad'))s.openDungeons.push('venerableRoad')}s.p.aperture.essence=essenceMax(s);note(s,`突破成功：${realm(s)}`,'major')}else{s.p.progress*=.72;s.p.hp-=8+s.p.rank*2;s.p.aperture.stability-=12;note(s,'突破失败，空窍震荡。','bad')}advance(s,4)}
function refine(s,uid){const g=s.gu.find(x=>x.uid===uid);if(!g||g.refined||g.hp<=0)err('蛊虫不可炼化');if(g.rank>s.p.rank)err('转数不足');const n=Math.max(8,g.rank*7);if(s.p.aperture.essence<n)err('真元不足');s.p.aperture.essence-=n;g.refine+=14+s.p.stats.refinement*.7+s.p.stats.will*.3+rng(s)*8;if(g.refine>=100){g.refine=100;g.refined=true;g.bond=20;if(!s.vital){s.vital=g.uid;ach(s,'firstGu')}note(s,`炼化${D.GU[g.id].name}。`,'good')}advance(s,2)}
function feed(s,uid){const g=s.gu.find(x=>x.uid===uid),f=g&&D.GU[g.id].food;if(!g||mat(s,f)<1)err('蛊食不足');mats(s,{[f]:-1});g.hunger-=55;g.hp+=8;g.bond+=2;advance(s,1)}
function canFuse(s,id){const f=D.FUSIONS[id];if(!f||!s.fusions.includes(id)||s.p.rank<f.rank)return false;for(const[g,n]of Object.entries(f.requires.gu||{}))if(s.gu.filter(x=>x.id===g).length<n)return false;for(const[m,n]of Object.entries(f.requires.materials||{}))if(mat(s,m)<n)return false;return true}
function fuse(s,id){const f=D.FUSIONS[id];if(!canFuse(s,id))err('融合条件不足');const use=[];for(const[g,n]of Object.entries(f.requires.gu||{}))use.push(...s.gu.filter(x=>x.id===g).slice(0,n));const vital=use.find(x=>x.uid===s.vital),dead=new Set(use.filter(x=>x!==vital).map(x=>x.uid));s.gu=s.gu.filter(x=>!dead.has(x.uid));for(const[m,n]of Object.entries(f.requires.materials||{}))mats(s,{[m]:-n});if(roll(s,C(f.chance+(s.p.stats.refinement-12)*.008+s.p.stats.luck*.002,.08,.95))){if(vital){vital.id=f.result;vital.rank=D.GU[f.result].rank;vital.refined=true;vital.refine=100}else addGu(s,f.result);ach(s,'fuse');note(s,`融合成功：${D.GU[f.result].name}`,'major')}else if(vital)vital.hp-=20;advance(s,4)}
function canLearnMove(s,id){const m=D.KILLER_MOVES[id];return!!m&&!s.moves.includes(id)&&s.p.rank>=m.rank&&m.requires.every(g=>hasGu(s,g))&&s.p.insight>=m.rank*8}
function learn(s,id){if(!canLearnMove(s,id))err('杀招条件不足');const m=D.KILLER_MOVES[id];s.p.insight-=m.rank*8;s.moves.push(id);ach(s,m.kind==='immortal'?'immortalMove':'mortalMove')}
function buy(s,kind,id,currency='stones'){const h=D.SHOPS[s.loc],t=currency==='immortal'?h?.immortal:h?.stones,n=t?.[kind]?.[id];if(n===undefined)err('这里没有此商品');const k=currency==='immortal'?'immortal':'stones';if(s.p[k]<n)err('货币不足');s.p[k]-=n;if(kind==='gu')addGu(s,id);else if(!s.bagEq.includes(id))s.bagEq.push(id);advance(s,1)}
function equip(s,id){const e=D.EQUIPMENT[id];if(!e||!s.bagEq.includes(id))err('没有此装备');if(s.p.rank<e.rank)err('境界不足');s.equip[e.slot]=id}
function travel(s,id){const a=D.LOCATIONS[s.loc],b=D.LOCATIONS[id];if(!b||!a.neighbors.includes(id))err('不是相邻地点');if(b.requiresFlag&&!s.flags[b.requiresFlag])err('道路未开启');if(s.p.rank<b.rank&&!s.openLoc.includes(id))err('境界不足');if(!s.openLoc.includes(id))s.openLoc.push(id);s.loc=id;if(!s.visited.includes(id))s.visited.push(id);if(id==='boneMountain'&&!s.openDungeons.includes('boneInheritance'))s.openDungeons.push('boneInheritance');if(id==='regionalGate'&&!s.openDungeons.includes('ancientBattle'))s.openDungeons.push('ancientBattle');advance(s,2)}
function gather(s){const t={school:{ink:1},village:{food:2,wood:1},guRoom:{petal:2,ore:1},dorm:{ink:1},inn:{food:2},bamboo:{wood:2,bone:1},river:{water:3,blood:1},crevice:{ore:2,formation:1},inheritanceCave:{ore:2,ink:1},marketRoad:{ore:2,food:2},boneMountain:{bone:4,beastCore:1},regionalGate:{formation:2},central:{ink:3},north:{beastCore:2},east:{immortalMaterial:1},west:{ore:4},immortalAuction:{immortalMaterial:1},tribulationField:{formation:2}};mats(s,t[s.loc]||{food:1});advance(s,3)}
function train(s){const k=Object.keys(s.p.stats)[Math.floor(rng(s)*6)];s.p.stats[k]+=.7;advance(s,3)}function rest(s){s.p.hp+=26;s.p.stamina+=70;s.p.spirit+=45;s.p.aperture.stability+=3;advance(s,8)}
function enterDungeon(s,id){const d=D.DUNGEONS[id];if(!d||!s.openDungeons.includes(id)||s.loc!==d.location)err('副本未开启');if(s.p.rank<d.minRank)err('境界不足');s.dungeon={id,room:1,danger:0};note(s,`进入副本「${d.name}」。`,'dungeon')}
function completeDungeon(s,id){const d=D.DUNGEONS[id];s.dungeon=null;if(!s.cleared.includes(id))s.cleared.push(id);s.p.stones+=d.rewards.stones||0;s.p.immortal+=d.rewards.immortalStones||0;mats(s,d.rewards.materials);if(d.rewards.gu&&!s.gu.some(g=>g.id===d.rewards.gu))addGu(s,d.rewards.gu);if(d.rewards.equipment&&!s.bagEq.includes(d.rewards.equipment))s.bagEq.push(d.rewards.equipment);if(id==='flowerWine'&&!s.fusions.includes('fourFlavorWine'))s.fusions.push('fourFlavorWine');if(id==='boneInheritance'&&!s.fusions.includes('blackWhiteBoar'))s.fusions.push('blackWhiteBoar');if(id==='landSpirit'&&!s.fusions.includes('immortalMoon'))s.fusions.push('immortalMoon');note(s,`通关${d.name}。`,'major');check(s)}
function dungeonStep(s,id){const r=s.dungeon,d=D.DUNGEONS[r?.id];if(!r)err('没有副本');if(id==='retreat'){s.dungeon=null;return}if(id==='search'){mats(s,{ore:2,bone:1});r.danger+=12;advance(s,1);return}const risk=C(.24+r.room*.07+r.danger*.004+(id==='force'?.15:-.08)-derived(s).agility*.003,.08,.78);if(roll(s,risk)){startBattle(s,'dungeon',r.id);return}r.room++;if(r.room>d.rooms)completeDungeon(s,d.id);else advance(s,id==='force'?1:2)}
function startBattle(s,source='wild',did=null){const r=Math.min(9,s.p.rank+(source==='tribulation'?1:0)),hp=45+r*38+(did?(s.dungeon?.room||1)*12:0);s.battle={source,did,name:source==='tribulation'?'天灾地劫':source==='dungeon'?'副本守关异兽':'山野异兽',hp,max:hp,atk:10+r*11,round:1}}
function battleOptions(s){const a=[{id:'strike',label:'近身攻伐',desc:'依靠自身与装备。'}];for(const g of s.gu.filter(g=>g.refined&&g.hp>0&&g.rank<=s.p.rank)){const d=D.GU[g.id];if(d.power)a.push({id:`gu:${g.uid}`,label:`催动${d.name}`,desc:`威力 ${d.power}`})}for(const id of s.moves){const m=D.KILLER_MOVES[id];a.push({id:`move:${id}`,label:m.name,desc:`威力 ${m.power}`})}return a.concat([{id:'guard',label:'防守',desc:'降低本回合伤害。'},{id:'flee',label:'脱离',desc:'敏捷越高越容易成功。'}])}
function battle(s,id){const b=s.battle,d=derived(s);if(!b)err('没有战斗');let dmg=0,guard=false;if(id==='strike')dmg=d.attack*.55;else if(id==='guard')guard=true;else if(id==='flee'){if(roll(s,C(.25+d.agility*.012,.08,.9))){s.battle=null;advance(s,2);return}}else if(id.startsWith('gu:')){const g=s.gu.find(x=>x.uid===id.slice(3)),q=D.GU[g?.id];if(!g||!g.refined)err('蛊虫不可用');if(q.kind==='immortal'){if(s.p.immortal<q.cost)err('仙元不足');s.p.immortal-=q.cost}else{if(s.p.aperture.essence<q.cost)err('真元不足');s.p.aperture.essence-=q.cost}dmg=q.power*(1+g.bond/180)}else if(id.startsWith('move:')){const m=D.KILLER_MOVES[id.slice(5)];if(m.kind==='immortal'){if(s.p.immortal<m.cost)err('仙元不足');s.p.immortal-=m.cost}else{if(s.p.aperture.essence<m.cost)err('真元不足');s.p.aperture.essence-=m.cost}dmg=m.power*(1+d.amp/100)}else err('无效战斗动作');b.hp-=dmg;if(b.hp<=0){const src=b.source,did=b.did;s.battle=null;s.p.stones+=10+s.p.rank*8;mats(s,{bone:2,blood:2});if(src==='tribulation'&&s.land){s.land.trib=72;s.p.immortal+=2;s.p.aperture.marks.light+=s.p.rank*5}else if(src==='dungeon'){s.dungeon.room++;if(s.dungeon.room>D.DUNGEONS[did].rooms)completeDungeon(s,did)}advance(s,2);return}s.p.hp-=Math.max(1,b.atk-d.defense*.45)*(guard?.45:1);b.round++;normal(s)}
function landAction(s,id){if(!s.land)err('没有福地');if(id==='develop'){if(s.p.immortal<1)err('仙元石不足');s.p.immortal--;s.land.nodes++}else if(id==='formation'){if(mat(s,'formation')<3)err('阵材不足');mats(s,{formation:-3});s.land.formation++;s.land.stability+=4}else if(id==='stabilize'){if(mat(s,'immortalMaterial')<1)err('仙材不足');mats(s,{immortalMaterial:-1});s.land.stability+=18;s.p.aperture.stability+=8}advance(s,6)}
function check(s){if(s.p.rep>=60)ach(s,'clanFriend');if(s.p.infamy>=60)ach(s,'clanEnemy');if(s.cleared.length>=4)ach(s,'dungeonMaster');if(s.p.rank>=9)ach(s,'rankNine')}
function finish(s,id){if(!D.ENDINGS[id])err('未知结局');s.ending=id;s.event=s.battle=s.dungeon=null;if(id==='reverseTime')ach(s,'secretEnding');note(s,`结局「${D.ENDINGS[id].name}」`,'ending')}
function context(s){if(s.ending)return{mode:'ending',title:D.ENDINGS[s.ending].name,text:D.ENDINGS[s.ending].desc};if(s.event){const e=ev[s.event];return{mode:'event',title:e.title,text:e.text,speaker:e.speaker}}if(s.battle)return{mode:'battle',title:s.battle.name,text:`第${s.battle.round}回合 · 对手生命 ${Math.max(0,Math.round(s.battle.hp))}/${s.battle.max}`};if(s.dungeon){const d=D.DUNGEONS[s.dungeon.id];return{mode:'dungeon',title:d.name,text:`第${s.dungeon.room}/${d.rooms}层 · ${d.desc}`}}return{mode:'free',title:D.LOCATIONS[s.loc].name,text:D.LOCATIONS[s.loc].desc}}
function choices(s){if(s.ending||!s.alive)return[{label:'重新开始',desc:'开启另一条路线。',cmd:{type:'ui',id:'new'}}];if(s.event)return ev[s.event].choices.filter(c=>!c.requiresGu||hasGu(s,c.requiresGu)).map(c=>({id:c.id,label:c.label,desc:c.text,cmd:{type:'event',id:c.id}}));if(s.battle)return battleOptions(s).map(x=>({...x,cmd:{type:'battle',id:x.id}}));if(s.dungeon)return['careful','force','search','retreat'].map(id=>({label:{careful:'谨慎推进',force:'强行突破',search:'搜索支路',retreat:'退出副本'}[id],desc:'副本行动',cmd:{type:'dungeon',id}}));const a=[],add=(label,desc,cmd,disabled='')=>a.push({label,desc,cmd,disabled});add('修炼',`${Math.floor(s.p.progress)}/${D.RANKS[s.p.rank].threshold}`,{type:'cultivate'},reason(s,'cultivate'));add('突破',`成功率约${Math.round(breakChance(s)*100)}%`,{type:'breakthrough'},reason(s,'breakthrough'));add('休息调养','恢复身体与精神',{type:'rest'});add('搜集资源','寻找当前地点蛊材',{type:'gather'});add('磨炼自身','随机强化基础属性',{type:'train'});for(const id of D.LOCATIONS[s.loc].neighbors){const l=D.LOCATIONS[id],lock=l.requiresFlag&&!s.flags[l.requiresFlag]||s.p.rank<l.rank&&!s.openLoc.includes(id);add(`前往 ${l.name}`,`${l.region} · 推荐${l.rank}转`,{type:'travel',id},lock?'道路未开启':'')}for(const g of s.gu){if(!g.refined)add(`炼化 ${D.GU[g.id].name}`,`${Math.floor(g.refine)}%`,{type:'refine',id:g.uid});if(g.hunger>=35)add(`喂养 ${D.GU[g.id].name}`,`饥饿${Math.floor(g.hunger)}%`,{type:'feed',id:g.uid},mat(s,D.GU[g.id].food)<1?'蛊食不足':'')}for(const id of s.fusions){const f=D.FUSIONS[id];add(`融合 ${D.GU[f.result].name}`,f.desc,{type:'fuse',id},canFuse(s,id)?'':'条件不足')}for(const[id,m]of Object.entries(D.KILLER_MOVES))if(!s.moves.includes(id)&&s.p.rank>=m.rank)add(`推演 ${m.name}`,m.desc,{type:'learn',id},canLearnMove(s,id)?'':'条件不足');for(const id of s.bagEq){const e=D.EQUIPMENT[id];if(s.equip[e.slot]!==id)add(`装备 ${e.name}`,e.desc,{type:'equip',id})}for(const id of s.openDungeons){const d=D.DUNGEONS[id];if(d.location===s.loc)add(`进入副本：${d.name}`,d.desc,{type:'enter',id})}const h=D.SHOPS[s.loc];if(h){for(const[id,n]of Object.entries(h.stones?.gu||{}))add(`购买 ${D.GU[id].name}`,`${n}元石`,{type:'buy',kind:'gu',id,currency:'stones'},s.p.stones<n?'元石不足':'');for(const[id,n]of Object.entries(h.stones?.equipment||{}))add(`购买 ${D.EQUIPMENT[id].name}`,`${n}元石`,{type:'buy',kind:'equipment',id,currency:'stones'},s.p.stones<n?'元石不足':'');for(const[id,n]of Object.entries(h.immortal?.gu||{}))add(`购买仙蛊 ${D.GU[id].name}`,`${n}仙元石`,{type:'buy',kind:'gu',id,currency:'immortal'},s.p.immortal<n?'仙元石不足':'')}if(s.land){add('福地：扩建资源点','消耗1仙元石',{type:'land',id:'develop'},s.p.immortal<1?'仙元石不足':'');add('福地：布置阵法','消耗3阵材',{type:'land',id:'formation'},mat(s,'formation')<3?'阵材不足':'')}return a}
function dispatch(s,c){const b=cp(s);try{({event:()=>chooseEvent(s,c.id),cultivate:()=>cultivate(s),breakthrough:()=>breakthrough(s),rest:()=>rest(s),gather:()=>gather(s),train:()=>train(s),travel:()=>travel(s,c.id),refine:()=>refine(s,c.id),feed:()=>feed(s,c.id),fuse:()=>fuse(s,c.id),learn:()=>learn(s,c.id),equip:()=>equip(s,c.id),buy:()=>buy(s,c.kind,c.id,c.currency),enter:()=>enterDungeon(s,c.id),dungeon:()=>dungeonStep(s,c.id),battle:()=>battle(s,c.id),land:()=>landAction(s,c.id)}[c.type]||(()=>err('未知指令')))();normal(s);check(s);return{ok:true}}catch(e){Object.keys(s).forEach(k=>delete s[k]);Object.assign(s,b);return{ok:false,message:e.message}}}
function save(s){return JSON.stringify({format:'gu-mud',version:D.VERSION,state:s})}function load(x){const z=JSON.parse(x);if(z?.format!=='gu-mud'||z.version!==D.VERSION)err('存档格式不兼容');normal(z.state);return z.state}
return{newGame,dispatch,choices,context,derived,realm,essenceMax,breakChance,day,save,load,hasGu,mat,canFuse,canLearnMove};
});