'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const D=require('../src/content.js'),E=require('../src/engine.js');
const clone=E.clone;
function started(seed='repeat'){const r=E.dispatch(E.newGame({seed}),{type:'choice',id:'school'});assert.ok(r.ok);return r.state;}
function run(s,c){const r=E.dispatch(s,c);assert.ok(r.ok,r.message);return r.state;}
function event(s,id){s=clone(s);s.pending={id,source:'测试前置选择'};s.combat=null;return s;}
function quiet(s){s=clone(s);s.queue=[];s.seen.shortage=1;s.seen.trail=1;s.seen.inheritance=1;s.pending=null;return s;}

test('four aptitudes use the original grade hierarchy',()=>{const caps=Object.keys(D.grades).map(grade=>E.capacity(E.newGame({grade})));assert.deepEqual(caps,[88,66,44,28]);assert.throws(()=>E.newGame({grade:'天灵根'}));});
test('opening starts with an unrefined Gu, not a fabricated spell',()=>{const s=E.newGame();assert.equal(s.gu.moon.tame,0);assert.equal(s.pending.id,'opening');assert.equal(s.v.rank,1);assert.equal(s.v.stage,0);});
test('134 state fields are counted at start, not hypothetical content',()=>{assert.equal(E.stats(E.newGame()).fields,134);assert.equal(D.events.length,23);assert.equal(E.stats(E.newGame()).choices,68);});
test('invalid action is atomic and does not consume RNG or time',()=>{const s=started(),before=JSON.stringify(s);const r=E.dispatch(s,{type:'action',id:'hunt'});assert.equal(r.ok,false);assert.strictEqual(r.state,s);assert.equal(JSON.stringify(s),before);});
test('pending decisions cannot be bypassed with travel or trading',()=>{const s=E.newGame();assert.equal(E.dispatch(s,{type:'travel',id:'village'}).ok,false);assert.equal(E.dispatch(s,{type:'action',id:'work'}).ok,false);});
test('same seed plus same choices produces byte-identical state',()=>{let a=quiet(started('same')),b=clone(a);for(const id of ['study','meditate','work','prepare']){a=run(a,{type:'action',id});b=run(b,{type:'action',id});}assert.deepEqual(a,b);});
test('save roundtrip preserves RNG, flags, memories and delayed events',()=>{let a=run(event(started(),'purse'),{type:'choice',id:'keep'});let b=E.validate(JSON.stringify(a));assert.deepEqual(a,b);a=run(a,{type:'action',id:'meditate'});b=run(b,{type:'action',id:'meditate'});assert.deepEqual(a,b);});
test('helping Fang Zheng unlocks a future rescue; charging him does not',()=>{let a=event(started('branch'),'classmate'),b=clone(a);a=run(a,{type:'choice',id:'help'});b=run(b,{type:'choice',id:'price'});a=event(a,'ambush');b=event(b,'ambush');const rescue=E.events.ambush.choices.find(c=>c.id==='friend');assert.equal(E.choiceReason(a,rescue),'');assert.notEqual(E.choiceReason(b,rescue),'');const after=run(a,{type:'choice',id:'friend'});assert.equal(after.flags.ambush,'rescued');assert.equal(after.npcs.fangzheng.favor,0);assert.equal(after.combat,null);assert.equal(E.dispatch(b,{type:'choice',id:'friend'}).ok,false);});
test('taking the purse queues an inquiry 48 hours later; returning it does not',()=>{const base=event(quiet(started()),'purse');const a=run(base,{type:'choice',id:'keep'}),b=run(base,{type:'choice',id:'return'});assert.equal(a.queue.find(q=>q.id==='purseAudit').due,base.clock+48);assert.ok(!b.queue.some(q=>q.id==='purseAudit'));let t=a;t.location='dorm';for(let i=0;i<6;i++)t=run(t,{type:'action',id:'rest'});assert.equal(t.pending.id,'purseAudit');assert.match(t.pending.source,/钱袋/);});
test('inadequate funds do not partially apply an event',()=>{const s=event(started(),'caravan');s.v.stones=3;const r=E.dispatch(s,{type:'choice',id:'reserve'});assert.equal(r.ok,false);assert.equal(r.state.v.stones,3);assert.equal(r.state.flags.caravan,'');assert.ok(!r.state.queue.some(q=>q.id==='order'));});
test('inheritance ownership is mutually exclusive and alters Gu acquisition',()=>{const base=event(quiet(started()),'inheritance');base.flags.trail='follow';base.location='cave';const self=run(base,{type:'choice',id:'self'}),shared=run(base,{type:'choice',id:'share'}),clan=run(base,{type:'choice',id:'clan'});assert.ok(self.gu.wine);assert.equal(shared.gu.wine,undefined);assert.equal(clan.gu.wine,undefined);assert.equal(self.flags.inheritance,'self');assert.equal(shared.flags.inheritance,'shared');assert.equal(clan.flags.inheritance,'clan');assert.ok(shared.queue.some(q=>q.id==='bargain'));assert.ok(clan.queue.some(q=>q.id==='clanReward'));});
test('unpaid deliveries change future relations and market prices',()=>{const base=event(quiet(started()),'delivery');base.bag.petals=20;const good=run(base,{type:'choice',id:'deliver'}),bad=run(base,{type:'choice',id:'steal'});assert.equal(good.bag.petals,0);assert.equal(bad.bag.petals,20);assert.ok(E.price(bad,'wine')>E.price(good,'wine'));assert.ok(bad.queue.some(q=>q.id==='merchantAfter'));assert.ok(!good.queue.some(q=>q.id==='merchantAfter'));});
test('a fulfilled reservation pays out once, never on repeated clicks',()=>{let s=event(quiet(started()),'order');s=run(s,{type:'choice',id:'keep'});const n=s.bag.wine;assert.equal(E.dispatch(s,{type:'choice',id:'keep'}).ok,false);assert.equal(s.bag.wine,n);});
test('debts cannot be repaid without sufficient funds',()=>{let s=event(quiet(started()),'debtDue');s.v.debt=8;s.v.stones=4;assert.equal(E.dispatch(s,{type:'choice',id:'pay'}).ok,false);s.v.stones=10;s=run(s,{type:'choice',id:'pay'});assert.equal(s.v.debt,0);assert.equal(s.v.stones,2);});
test('labor repayment reduces debt instead of minting income',()=>{let s=quiet(started());s.flags.debtDue='labor';s.v.debt=2;const money=s.v.stones;s=run(s,{type:'action',id:'work'});assert.equal(s.v.stones,money);assert.ok(s.v.debt<2);});
test('travel adjacency and hidden entrance requirements are enforced',()=>{let s=quiet(started());assert.equal(E.dispatch(s,{type:'travel',id:'cave'}).ok,false);s.location='river';assert.equal(E.dispatch(s,{type:'travel',id:'crevice'}).ok,false);s.v.clue=30;s=run(s,{type:'travel',id:'crevice'});assert.equal(s.location,'crevice');assert.equal(E.dispatch(s,{type:'travel',id:'cave'}).ok,false);});
test('location-dependent queued events wait rather than disappearing',()=>{let s=quiet(started());s.location='dorm';s.queue=[{id:'classmate',due:s.clock,source:'旧事'}];s=run(s,{type:'action',id:'meditate'});assert.equal(s.pending,null);assert.equal(s.queue.length,1);s=run(s,{type:'travel',id:'school'});assert.equal(s.pending.id,'classmate');});
test('Gu refinement works, and the first success is the vital Gu',()=>{let s=quiet(started());for(let i=0;i<10&&s.gu.moon.tame<100;i++){s=run(s,{type:'refine',id:'moon'});}assert.equal(s.gu.moon.tame,100);assert.equal(s.gu.moon.vital,true);});
test('partial refinement decays but successful refinement does not',()=>{let s=quiet(started());s.gu.moon.tame=50;s=run(s,{type:'action',id:'meditate'});assert.ok(s.gu.moon.tame<50);s.gu.moon.tame=100;s=run(s,{type:'action',id:'meditate'});assert.equal(s.gu.moon.tame,100);});
test('moon Gu eats two petals or one petal and one heart grass',()=>{let s=quiet(started());s.gu.moon.hunger=80;const old=s.bag.petals;s=run(s,{type:'feed',id:'moon'});assert.equal(s.bag.petals,old-2);s.gu.moon.hunger=80;s.bag.grass=1;s=run(s,{type:'feed',id:'moon'});assert.equal(s.bag.petals,old-3);assert.equal(s.bag.grass,0);});
test('starvation can kill vital Gu and injure its owner',()=>{let s=quiet(started());s.autoFeed=false;s.gu.moon={...s.gu.moon,tame:100,hunger:100,health:1,vital:true};s=run(s,{type:'action',id:'meditate'});assert.equal(s.gu.moon.health,0);assert.ok(s.v.injury>=20);assert.ok(s.v.health<=65);});
test('the one-rank wine worm does not give unlimited later-rank bonuses',()=>{let s=quiet(started());s.gu.wine={...s.gu.moon,tame:100};s.v.rank=2;assert.equal(E.dispatch(s,{type:'purify'}).ok,false);});
test('buy then sell loses money and conserves traded inventory',()=>{let s=quiet(started());s.location='inn';const before=s.v.stones,stock=s.market.wine,bag=s.bag.wine;s=run(s,{type:'trade',id:'wine',qty:1,mode:'buy'});s=run(s,{type:'trade',id:'wine',qty:1,mode:'sell'});assert.ok(s.v.stones<before);assert.equal(s.market.wine,stock);assert.equal(s.bag.wine,bag);});
test('negative or fractional trade quantities are rejected',()=>{const s=quiet(started());s.location='inn';for(const qty of [-1,0,.5,100,NaN])assert.equal(E.dispatch(s,{type:'trade',id:'wine',qty,mode:'buy'}).ok,false);});
test('combat is turn based, consumes essence, and blocks unrelated actions',()=>{let s=quiet(started());s.location='bamboo';s.gu.moon.tame=100;s=run(s,{type:'action',id:'hunt'});assert.ok(s.combat);assert.equal(E.dispatch(s,{type:'action',id:'rest'}).ok,false);const essence=s.v.essence;s=run(s,{type:'combat',id:'moon'});assert.equal(s.v.essence,essence-8);assert.equal(s.combat.round,1);assert.equal(s.ledger.combatTurns,1);});
test('death stops the hour loop and disallows further play',()=>{let s=quiet(started());s.autoEat=false;s.v.health=1;s.v.thirst=100;s.bag.water=0;const t=s.clock;s=run(s,{type:'action',id:'meditate'});assert.equal(s.alive,false);assert.equal(s.clock,t+1);assert.equal(E.dispatch(s,{type:'action',id:'work'}).ok,false);assert.ok(E.validate(JSON.stringify(s)));});
test('daily state advances exactly once at a date boundary',()=>{let s=quiet(started());s.clock=23;const before=s.npcs.jiangya.progress;s=run(s,{type:'action',id:'meditate'});assert.equal(s.clock,25);assert.equal(s.npcs.jiangya.progress,before+3);});
test('rank cannot overflow the implemented five-rank range',()=>{const s=quiet(started());s.v.rank=5;s.v.stage=3;s.v.progress=100;assert.equal(E.dispatch(s,{type:'action',id:'breakthrough'}).ok,false);});
test('unaffordable social help and repeated conversations are gated',()=>{let s=quiet(started());assert.equal(E.dispatch(s,{type:'social',id:'fangzheng',mode:'ask'}).ok,false);s=run(s,{type:'social',id:'fangzheng',mode:'chat'});assert.equal(E.dispatch(s,{type:'social',id:'fangzheng',mode:'chat'}).ok,false);});
test('invalid, old, poisoned, incomplete and non-finite saves are rejected',()=>{assert.throws(()=>E.validate('not JSON'));assert.throws(()=>E.validate('{"version":1}'));const original=started();for(const mutate of [s=>delete s.v.health,s=>s.v.health=-1,s=>s.location='fake',s=>s.npcs.fangyuan.memory=[null],s=>s.pending={id:'missing',source:''},s=>s.gu.moon.health='bad',s=>s.rng=0,s=>s.history=[{}],s=>s.bag.food=.3]){const s=clone(original);mutate(s);assert.throws(()=>E.validate(JSON.stringify(s)));}assert.throws(()=>E.validate('{"version":2,"__proto__":{"polluted":true}}'));assert.equal({}.polluted,undefined);});
test('data graph has unique ids and all references resolve',()=>{assert.equal(new Set(D.events.map(e=>e.id)).size,D.events.length);for(const e of D.events){assert.equal(new Set(e.choices.map(c=>c.id)).size,e.choices.length);for(const c of e.choices){for(const[id]of c.effects.schedule||[])assert.ok(E.events[id],id);for(const k of Object.keys(c.effects.set||{}))assert.ok(D.flagKeys.includes(k),k);for(const k of Object.keys(c.effects.items||{}))assert.ok(D.goods[k],k);}}for(const[id,l]of Object.entries(D.locations))for(const n of l.neighbors)assert.ok(D.locations[n].neighbors.includes(id));});
test('simulated multi-seed campaigns remain serializable with valid bounds',()=>{for(let seed=1;seed<=12;seed++){let s=E.newGame({seed});for(let i=0;i<180&&s.alive;i++){let command;if(s.pending){const options=E.events[s.pending.id].choices.filter(c=>!E.choiceReason(s,c));assert.ok(options.length);command={type:'choice',id:options[(i+seed)%options.length].id};}else if(s.combat)command={type:'combat',id:s.gu.moon.tame===100&&s.v.essence>=8?'moon':'escape'};else{const list=D.actions.filter(a=>!E.actionReason(s,a.id));command={type:'action',id:list[(i*7+seed)%list.length].id};if(i%9===0){const next=D.locations[s.location].neighbors.filter(id=>E.meets(s,D.locations[id].require));command={type:'travel',id:next[(i+seed)%next.length]};}}s=run(s,command);assert.ok(E.validate(JSON.stringify(s)));}assert.ok(s.ledger.actions>0);}});
