/* 0.5 player-agency adapter. Adds world hotspots and a free-action command bar.
   Execution still happens by clicking existing data-cmd commands handled by app.js. */
(()=>{
'use strict';
const D=window.GuContent,E=window.GuEngine,A=window.GuAgency,KEY='gu_qingmao_v2_auto';
if(!D||!E||!A)return;
const app=document.getElementById('app'),notice=document.getElementById('notice');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const enc=x=>esc(JSON.stringify(x));
function state(){try{const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw):null;}catch{return null;}}
function toast(text){if(!notice)return;notice.textContent=text;notice.classList.add('visible');clearTimeout(toast.t);toast.t=setTimeout(()=>notice.classList.remove('visible'),4200);}
function execute(command){const b=document.createElement('button');b.hidden=true;b.dataset.cmd=JSON.stringify(command);document.body.appendChild(b);b.click();b.remove();}
function validCommand(s,o){if(o.disabled)return false;const c=o.command;if(!c)return false;if(c.type==='travel')return D.locations[s.location].neighbors.includes(c.id)&&E.meets(s,D.locations[c.id].require);if(c.type==='action')return !E.actionReason(s,c.id);if(c.type==='refine'){const g=s.gu[c.id];return !!g&&g.health>0&&g.tame<100&&s.v.essence>=10;}if(c.type==='feed'){const g=s.gu[c.id];return !!g&&g.health>0&&g.hunger>=15;}if(c.type==='trade')return !!D.locations[s.location].market;if(c.type==='social')return true;return true;}
function hotspots(s){return A.objectsFor(s).map(o=>{const enabled=validCommand(s,o);const attrs=o.person?`data-v4-person="${esc(o.person)}"`:`data-cmd="${enc(o.command)}"`;const detail=A.preview(s,o.command);return `<button class="agency-hotspot ${o.person?'person':'object'}" style="left:${o.x}%;top:${o.y}%" ${attrs} ${enabled?'':'disabled'} aria-label="${esc(o.label)}"><span class="agency-ring"><b>${esc(o.glyph)}</b></span><span class="agency-label"><strong>${esc(o.label)}</strong><small>${esc(detail||o.description)}</small></span></button>`;}).join('');}
function thoughts(s){const items=A.voices(s);if(!items.length)return'';return `<aside class="agency-thoughts"><div class="agency-thought-head">你意识到……</div>${items.map((x,i)=>`<article style="--delay:${i*80}ms"><strong>${esc(x.voice)}</strong><p>${esc(x.text)}</p></article>`).join('')}</aside>`;}
function suggestions(s){const byLoc={school:['和方正说话','听课','练习月刃','去蛊室'],room:['问江牙蛊食','买月兰花瓣','买草人傀儡','回学堂'],dorm:['炼化月光蛊','冥想','休息','回学堂'],village:['去学堂','去客栈','去竹林','做杂务'],inn:['休息','做杂务','去酒肆','回山寨'],shop:['买青竹酒','买米酒','回客栈'],bamboo:['观察脚印','远远跟着方源','洒青竹酒引蛊','去河滩'],river:['观察足迹','取水','去石缝','回竹林'],crevice:['观察更深处','进入山壁','回河滩'],cave:['搜索遗留痕迹','回石缝']};return(byLoc[s.location]||['观察周围','修炼','冥想']).slice(0,4);}
function commandBar(s){return `<section class="agency-command"><div class="agency-command-main"><span class="agency-prompt">你想做什么？</span><input id="agency-input" maxlength="80" autocomplete="off" placeholder="例如：远远跟着方源 / 观察脚印 / 去河滩" aria-label="自由行动"><button id="agency-submit">行动</button></div><div id="agency-preview" class="agency-preview">不用猜固定命令；写自然中文即可。当前由本地意图解析，之后可无缝接 AI。</div><div class="agency-suggestions">${suggestions(s).map(x=>`<button data-agency-suggest="${esc(x)}">${esc(x)}</button>`).join('')}<button data-agency-fallback>显示全部动作</button></div></section>`;}
function explain(text,s){const r=A.parse(text,s),box=document.getElementById('agency-preview');if(!box)return r;if(!r.ok){box.className='agency-preview unknown';box.textContent=r.message;return r;}const detail=A.preview(s,r.command);box.className='agency-preview understood';box.innerHTML=`<strong>理解为：${esc(r.label)}</strong>${detail?`<span>${esc(detail)}</span>`:''}${r.note?`<em>${esc(r.note)}</em>`:''}`;return r;}
function submit(){const s=state(),input=document.getElementById('agency-input');if(!s||!input)return;const r=explain(input.value,s);if(!r.ok){toast(r.message);return;}execute(r.command);}
function enhance(){const s=state(),stage=document.querySelector('.stage.v4-play');document.querySelectorAll('.agency-layer,.agency-thoughts,.agency-command').forEach(x=>x.remove());if(!s||!stage||s.pending||s.combat||!s.alive)return;stage.classList.add('agency-mode');const layer=document.createElement('div');layer.className='agency-layer';layer.innerHTML=hotspots(s);stage.appendChild(layer);stage.insertAdjacentHTML('beforeend',thoughts(s)+commandBar(s));const fallback=stage.querySelector('.v4-freeplay');if(fallback)fallback.classList.add('agency-fallback-panel');}
let scheduled=false;const observer=new MutationObserver(()=>{if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;enhance();});});observer.observe(app,{childList:true,subtree:true});
document.addEventListener('input',e=>{if(e.target.id==='agency-input'){const s=state();if(s)explain(e.target.value,s);}});
document.addEventListener('keydown',e=>{if(e.target.id==='agency-input'&&e.key==='Enter'){e.preventDefault();submit();}});
document.addEventListener('click',e=>{if(e.target.closest('#agency-submit')){submit();return;}const sug=e.target.closest('[data-agency-suggest]');if(sug){const input=document.getElementById('agency-input'),s=state();if(input&&s){input.value=sug.dataset.agencySuggest;input.focus();explain(input.value,s);}return;}if(e.target.closest('[data-agency-fallback]')){document.querySelector('.agency-fallback-panel')?.classList.toggle('show');return;}});
enhance();
})();
