/* Browser adapter: all imported/player-authored text is HTML-escaped. */
(()=>{
'use strict';
const D=GuContent,E=GuEngine,KEY='gu_qingmao_v2_',OLD='gu_dao_ni_ming_lu_v1';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>Number(x).toLocaleString('zh-CN',{maximumFractionDigits:1});
const btn=(text,cmd,disabled=false,cls='')=>`<button class="${cls}" data-cmd="${esc(JSON.stringify(cmd))}" ${disabled?'disabled':''}>${text}</button>`;
const relationName={trust:'信任',fear:'畏惧',anger:'敌意',favor:'人情',resources:'元石',power:'实力',progress:'修行'};
const sourceLink=path=>'https://github.com/Liang-techh/gu/blob/main/'+path.split('/').map(encodeURIComponent).join('/');
let s=E.newGame(),tab='act',noticeTimer,lastSaved=null,autosavePaused=false,hasGame=false,initialWarning='';
const app=document.getElementById('app'),dialog=document.getElementById('dialog');
function notice(text){const n=document.getElementById('notice');n.textContent=text;n.classList.add('visible');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>n.classList.remove('visible'),5500);}
function storageGet(key){try{return localStorage.getItem(key);}catch{return null;}}
function persist(key=KEY+'auto',explicit=false){
 try{const raw=JSON.stringify(s);if(key===KEY+'auto'&&!explicit){const existing=localStorage.getItem(key);if(autosavePaused||(lastSaved!==null&&existing!==lastSaved)){autosavePaused=true;notice('另一页面改写了存档，自动保存已暂停。请先导出或手动存档。');return false;}}
 localStorage.setItem(key,raw);if(key===KEY+'auto')lastSaved=raw;return true;
 }catch{notice('浏览器不允许写入存档，或空间已满。请使用“导出存档”保存到文件。');return false;}
}
function meter(label,value,max=100,style=''){return `<div class="meter"><div class="line"><span>${label}</span><span>${fmt(value)} / ${fmt(max)}</span></div><div class="track ${style}" role="meter" aria-label="${label}" aria-valuemin="0" aria-valuemax="${max}" aria-valuenow="${value}"><i style="width:${Math.max(0,Math.min(100,value/max*100))}%"></i></div></div>`;}
function when(clock){return `第${Math.floor(clock/24)+1}日 ${String(clock%24).padStart(2,'0')}:00`;}
function charPanel(){return `<aside class="panel character"><div class="overview"><div class="eyebrow">空窍 · 元海</div><h2>${esc(s.name)}</h2><span class="badge gold">${['','一','二','三','四','五'][s.v.rank]}转${D.stages[s.v.stage]}</span> <span class="badge">${Object.keys(D.grades).find(k=>D.grades[k]===s.v.aptitude)||'资质'} ${fmt(s.v.aptitude)}%</span><div class="balance"><span class="hint">元石</span><strong>${fmt(s.v.stones)}</strong></div></div><div class="vitals">${meter('身体',s.v.health,100,s.v.health<30?'bad':'')}${meter('真元',s.v.essence,E.capacity(s),'gold')}${meter('修为',s.v.progress,100,'gold')}${meter('疲劳',s.v.fatigue,100,s.v.fatigue>70?'bad':'')}</div><div class="extras"><div class="line small"><span>饥饿 / 口渴</span><span>${fmt(s.v.hunger)} / ${fmt(s.v.thirst)}</span></div><div class="line small"><span>伤势 / 中毒</span><span>${fmt(s.v.injury)} / ${fmt(s.v.poison)}</span></div><div class="line small"><span>家族评价 / 怀疑</span><span>${fmt(s.v.reputation)} / ${fmt(s.v.suspicion)}</span></div><div class="line small"><span>尚欠元石</span><span>${fmt(s.v.debt)}</span></div><div class="divider"></div><div class="settings"><label><input type="checkbox" data-setting="autoFeed" ${s.autoFeed?'checked':''}>自动养蛊</label><label><input type="checkbox" data-setting="autoEat" ${s.autoEat?'checked':''}>自动饮食</label></div><details><summary class="small">查看全部变量及用途</summary><div class="statbook">${Object.entries(D.variables).map(([k,v])=>`<div class="line"><span>${v[0]}</span><span>${fmt(s.v[k])}</span></div><p>${v[4]}</p>`).join('')}</div></details></div></aside>`;}
function reqText(req){return(req||[]).map(([path,op,value])=>{const p=path.split('.');let name=path;if(p[0]==='v')name=D.variables[p[1]]?.[0]||path;if(p[0]==='bag')name=D.goods[p[1]]?.name||path;if(p[0]==='gu')name=(D.gus[p[1]]?.name||p[1])+'炼化';if(p[0]==='npcs')name=(D.people[p[1]]?.name||p[1])+'·'+(relationName[p[2]]||p[2]);return `${name} ${op==='>='?'至少':op==='<='?'至多':'为'} ${value}`;}).join('；');}
function preview(c){const f=c.effects,parts=[];for(const[k,v]of Object.entries(f.add||{}))parts.push(`${D.variables[k][0]} ${v>=0?'+':''}${v}`);for(const[k,v]of Object.entries(f.items||{}))parts.push(`${D.goods[k].name} ${v>=0?'+':''}${v}`);for(const[k,n]of Object.entries(f.relation||{}))for(const[field,v]of Object.entries(n))if(['trust','anger','favor'].includes(field))parts.push(`${D.people[k].name}${relationName[field]} ${v>=0?'+':''}${v}`);if(f.gu)parts.push('获得尚未炼化的'+D.gus[f.gu].name);if(f.schedule)parts.push('此事将有后续');if(f.combat)parts.push('进入战斗');if(f.special==='repay')parts.push('需偿还 '+fmt(s.v.debt)+' 元石');return parts.slice(0,6).join(' · ');}
function story(){const e=E.events[s.pending.id];return `<section class="story-box" aria-label="当前事件"><div class="eyebrow">眼前之事 · 等待你的选择</div><h2>${e.title}</h2>${s.pending.source?`<div class="source-tag">缘起：${esc(s.pending.source)}</div>`:''}<p class="narrative">${e.text}</p><div class="choices">${e.choices.map((c,i)=>{const reason=E.choiceReason(s,c);return btn(`<strong><span class="index">0${i+1}</span>${c.label}</strong><small>${esc(preview(c))}</small>${c.requires?`<small>条件：${esc(reqText(c.requires))}</small>`:''}${reason?`<small class="locked">${esc(reason)}</small>`:''}`,{type:'choice',id:c.id},!!reason,'choice');}).join('')}</div></section>`;}
function combat(){const c=s.combat;return `<section class="story-box"><div class="eyebrow">交锋 · 第 ${c.round+1} 回合</div><h2>${esc(c.name)}</h2><p class="hint">真元、疲劳、准备、伤势与月刃练习都会参与结算。防守不能无限恢复体力。</p><div class="line"><span>对方身体</span><span>${c.health} / ${c.maxHealth}</span></div><div class="combat-health"><i style="width:${c.health/c.maxHealth*100}%"></i></div><div class="actions">${[['strike','近身攻击','依靠力量，不消耗真元'],['moon','催动月光蛊','消耗八点真元，练习越多越稳'],['guard','防守','大幅减轻本回合受到的伤害'],['escape','逃离','敏捷与准备提高成功率；失败会受击']].map(([id,name,hint])=>btn(`<b>${name}</b><small>${hint}</small>`,{type:'combat',id},id==='moon'&&(s.v.essence<8||!s.gu.moon||s.gu.moon.tame<100||s.gu.moon.health<=0),'action')).join('')}</div></section>`;}
function actTab(){const loc=D.locations[s.location];let html=`<div class="location-title"><h2>${loc.name}</h2><span class="badge">${loc.safe?'山寨之内':'山寨之外'}</span></div><p class="hint">${loc.description}</p>`;
 if(!s.alive)return html+`<div class="story-box"><h2>此局已终</h2><p class="narrative">你留下的往事仍可翻阅。另一条路，要从下一次开局开始。</p>${btn('重新开局',{type:'ui',id:'new'},false,'primary')}</div>`;
 if(s.pending)return html+story();if(s.combat)return html+combat();
 const goal=s.gu.moon.tame<100?'先在“蛊虫”中炼化月光蛊；真元不足时，可汲取元石或休息。':s.flags.trail===''?'到竹林以青竹酒引蛊，或者留在学堂积累练习、关系与元石。':s.flags.trail==='follow'&&s.flags.inheritance===''?'酒虫的踪迹通向河滩后的石缝，继续深入才能处置遗藏。':'你的往事已开始影响后来。继续修炼、探索和经营人际关系。';
 html+=`<div class="lead">${goal}</div><h3>现在做什么</h3><div class="actions">${D.actions.filter(a=>!a.locations||a.locations.includes(s.location)).map(a=>{const reason=E.actionReason(s,a.id);return btn(`<b>${a.name}</b><span>${a.hours} 小时</span><small>${esc(reason||a.hint)}</small>`,{type:'action',id:a.id},!!reason,'action');}).join('')}</div><div class="divider"></div><h3>附近</h3><div class="toolbar">${loc.neighbors.map(id=>btn(D.locations[id].name+' →',{type:'travel',id},!E.meets(s,D.locations[id].require))).join('')}</div>`;return html;
}
function mapTab(){const locked=!!s.pending||!!s.combat||!s.alive;return `<h2>青茅山</h2><p class="hint">沿相邻地点移动。每一步都推进时间；石缝与深处的入口需要线索。当前地图不假装覆盖五域。</p><div class="map">${Object.entries(D.locations).map(([id,l])=>`<div class="card ${id===s.location?'current':''}"><h3>${l.name}${id===s.location?'<span class="badge gold">所在</span>':''}</h3><p class="hint">${l.description}</p><div class="hint">相连：${l.neighbors.map(k=>D.locations[k].name).join('、')}</div>${l.require?`<small class="muted">${esc(reqText(l.require))}</small>`:''}${btn(id===s.location?'此刻所在':D.locations[s.location].neighbors.includes(id)?'前往':'须沿路前往',{type:'travel',id},locked||id===s.location||!D.locations[s.location].neighbors.includes(id)||!E.meets(s,l.require))}</div>`).join('')}</div>`;}
function guTab(){const locked=!!s.pending||!!s.combat||!s.alive;return `<h2>炼蛊 · 用蛊 · 养蛊</h2><p class="hint">第一次炼化成功的蛊成为本命蛊。未炼成时，停手会遭到蛊虫意志抵抗，炼化进度逐时回退。饥饿至极会损伤蛊虫；本命蛊死亡会反噬蛊师。</p><div class="cards">${Object.entries(s.gu).map(([id,g])=>`<article class="card"><h3>${D.gus[id].name}<span class="badge ${g.vital?'gold':''}">${g.health<=0?'已死':g.vital?'本命蛊':g.tame>=100?'已炼化':'未炼化'}</span></h3><p class="hint">${D.gus[id].description}</p>${meter('炼化',g.tame)}<div class="mini-grid"><div><small>生机</small>${fmt(g.health)}</div><div><small>饥饿</small>${fmt(g.hunger)}</div><div><small>练习</small>${fmt(g.practice)}</div></div><div class="buttons">${btn('炼化 · 二小时',{type:'refine',id},locked||g.health<=0||g.tame>=100||s.v.essence<10)}${btn('喂养',{type:'feed',id},locked||g.health<=0||g.hunger<15)}${id==='wine'?btn('精炼真元',{type:'purify'},locked||g.health<=0||g.tame<100||s.v.rank!==1||s.v.essence<10):''}</div></article>`).join('')}</div><div class="divider"></div><h3>行囊</h3>${Object.entries(s.bag).map(([id,n])=>`<div class="line"><span>${D.goods[id].name}</span><span>${n} ${['food','water'].includes(id)?btn('使用',{type:'eat',id},locked||n<1):''}</span></div>`).join('')}<p class="hint">本版实装月光蛊和酒虫；不以未经核对的蛊名、食料或蛊方填充目录。</p>`;}
function peopleTab(){const locked=!!s.pending||!!s.combat||!s.alive;return `<h2>人物往来</h2><p class="hint">信任不是元石，也不是人情。有人收了礼仍不愿为你作证；一次真正的帮助，可能换来日后的援手。人物每天积累资源与修行进度。</p><div class="cards">${Object.entries(D.people).map(([id,p])=>{const n=s.npcs[id],here=p.location===s.location&&(id!=='jiafu'||E.day(s)<12===false);return `<article class="card"><h3>${p.name}<span class="badge">${here?'在此处':D.locations[p.location].name}</span></h3><p class="hint">所重：${p.goal}${id==='jiafu'&&E.day(s)<12?' · 商队尚未到来':''}</p><div class="mini-grid">${['trust','fear','anger','favor','resources','power'].map(k=>`<div><small>${relationName[k]}</small>${fmt(n[k])}</div>`).join('')}</div>${n.memory.length?`<p class="hint">他记得：${esc(n.memory[n.memory.length-1].text)}</p>`:'<p class="hint">你们还没有值得记下的往来。</p>'}<div class="buttons">${btn('交谈',{type:'social',id,mode:'chat'},locked||!here)}${btn('赠一块元石',{type:'social',id,mode:'gift'},locked||!here||s.v.stones<1)}${btn('请他相助',{type:'social',id,mode:'ask'},locked||!here||n.trust<15||n.favor<1||n.resources<2)}</div></article>`;}).join('')}</div>`;}
function tradeTab(){const market=D.locations[s.location].market,locked=!market||!!s.pending||!!s.combat||!s.alive;return `<h2>买卖与食料</h2><p class="hint">价格受物资、怀疑和交易关系影响。买入、卖出均消耗一小时；卖价低于买价。存货不是无限的。</p>${!market?'<div class="status-note">这里没有商铺。请前往蛊室、客栈或酒肆。</div>':''}<div class="table-wrap"><table class="rowtable"><thead><tr><th>物资</th><th>行囊 / 存货</th><th>买 / 卖</th><th>交易</th></tr></thead><tbody>${Object.entries(D.goods).map(([id,g])=>`<tr><td class="itemname">${g.name}</td><td>${s.bag[id]} / ${s.market[id]}</td><td>${E.price(s,id).toFixed(2)} / ${E.price(s,id,true).toFixed(2)}</td><td>${btn('买 1',{type:'trade',id,qty:1,mode:'buy'},locked||s.market[id]<1||s.v.stones<E.price(s,id))} ${btn('买 5',{type:'trade',id,qty:5,mode:'buy'},locked||s.market[id]<5||s.v.stones<E.price(s,id)*5)} ${btn('卖 1',{type:'trade',id,qty:1,mode:'sell'},locked||s.bag[id]<1)}</td></tr>`).join('')}</tbody></table></div><div class="divider"></div><div class="line"><span>物资充足</span><span>${fmt(s.v.supply)}</span></div><div class="line"><span>商队信任</span><span>${fmt(s.v.caravanTrust)}</span></div><p class="hint">月兰花瓣初始基价每片 0.1 元石；青竹酒每坛 2 元石。动态价格属于游戏规则，不是原著逐笔账目复刻。</p>`;}
function historyTab(){return `<h2>往事与后果</h2><p class="hint">即时得失记在这里；未了的事不会因为读档而消失。最近保留四百次行动，长期关系与剧情标记单独保存。</p><details><summary>尚有 ${s.queue.length} 桩未了事</summary>${s.queue.map(q=>`<div class="feed"><time>${q.due>s.clock?'至少再过 '+(q.due-s.clock)+' 小时':'时机已到，等待相应地点'}</time>${esc(q.source)}<div class="hint">${E.events[q.id].locations?'须在 '+E.events[q.id].locations.map(k=>D.locations[k].name).join(' / ')+' 相遇':'之后可能有人前来'}</div></div>`).join('')}</details><div class="divider"></div>${s.history.length?s.history.slice().reverse().map(h=>`<article class="history"><small>${when(h.at)} ${h.kind==='choice'?'· 一次选择':''}</small><h3>${esc(h.description)}</h3><div class="chips">${h.changes.slice(0,16).map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div>${h.flags.length?'<p class="hint">这次行动改变了之后可走的分支。</p>':''}</article>`).join(''):'<p class="empty">你的第一步还未落下。</p>'}`;}
function sourceTab(){return `<h2>原文与改编</h2><div class="lead">专有名词有出处；新的选择与后果是同人改编，不是小说中已经发生的情节。</div><p class="hint">原文保留在仓库 reference/novel 中。本版逐项核对下列已用术语，不宣称已经完整考据全部章节。普通界面说明使用现代中文，不把原创剧情伪装成原文引用。</p><h3>可点击核对的原文用词 · ${D.sources.length} 项</h3><div class="terms">${D.sources.map(x=>`<a href="${sourceLink(x.path)}" target="_blank" rel="noopener noreferrer" title="第一卷，第${x.chapter}章">${x.term}<small> · ${x.chapter}</small></a>`).join('')}</div><div class="divider"></div><h3>本版边界</h3><p class="hint">青茅山内 ${Object.keys(D.locations).length} 个可达地点，${D.events.length} 个剧情节点，${D.events.reduce((n,e)=>n+e.choices.length,0)} 个条件选项，${Object.keys(D.people).length} 位原著人物。实装两种蛊虫，一至五转修行。这里没有未经实现的五域旅行、蛊仙经营、自由文本人工智能或全书结局。</p><p class="hint">资质、真元、炼化与喂养遵循已核对的核心区别；战斗、成长速度、市场浮动、人物数值和事件日程是可测试的游戏化模型。日程按小时推进，不把游戏日程当作原著历法。</p><p class="hint">旧版使用独立存档键，不自动迁移含自设名词的旧档，也不删除旧档。可在 Git 历史中取回旧版游戏。</p>`;}
function render(){const count=E.stats(s),loc=D.locations[s.location];app.innerHTML=`<div class="shell"><header><div class="brand"><div class="seal" aria-hidden="true">蛊</div><div><strong>蛊真人</strong><div class="eyebrow">青茅山 · 文字沙盒 / 0.2</div></div></div><div class="toolbar">${btn('存读档',{type:'ui',id:'saves'},false,'quiet')}${btn('导出存档',{type:'ui',id:'export'},false,'quiet')}${btn('重新开局',{type:'ui',id:'new'},false,'quiet')}</div></header><section class="hero"><div><div class="eyebrow">人是万物之灵，蛊是天地之精</div><h1>走自己的路。</h1><p>修炼与养蛊，利益与人情。你眼前的一次选择，可能在数日后的另一处，重新找上你。</p></div><div class="hero-meta"><div class="date">第 ${E.day(s)} 日</div><div>${String(s.clock%24).padStart(2,'0')}:00 · ${s.weather}</div><div class="hint">${loc.name} · ${s.alive?'修行中':'此局已终'}</div></div></section>${initialWarning?`<div class="status-note">${esc(initialWarning)}</div>`:''}${autosavePaused?'<div class="status-note">自动保存已暂停，防止覆盖另一页面的进度。请先手动存档或导出。</div>':''}<main class="layout">${charPanel()}<section class="panel center"><nav class="tabbar" aria-label="游戏页面">${[['act','行止'],['map','青茅山'],['gu','蛊虫'],['people','人物'],['trade','买卖'],['history','往事'],['sources','原文']].map(([id,name])=>btn(name,{type:'ui',id:'tab',value:id},false,id===tab?'selected':'')).join('')}</nav><div class="stage">${tab!=='act'&&(s.pending||s.combat)?`<div class="status-note">有${s.combat?'一场战斗':'一件事情'}等待处理。${btn('回到行止',{type:'ui',id:'tab',value:'act'})}</div>`:''}${({act:actTab,map:mapTab,gu:guTab,people:peopleTab,trade:tradeTab,history:historyTab,sources:sourceTab}[tab]||actTab)()}</div></section><aside class="panel sidebar"><h3>近事</h3><div class="recent">${s.log.slice(-6).reverse().map(l=>`<div class="feed ${esc(l.kind)}"><time>${when(l.at)}</time>${esc(l.text)}${l.source?`<div class="hint">缘起：${esc(l.source)}</div>`:''}</div>`).join('')}</div><div class="divider"></div><div class="line hint"><span>未了之事</span><span>${s.queue.length}</span></div><div class="line hint"><span>已作选择</span><span>${s.ledger.choices}</span></div><div class="line hint"><span>已到地点</span><span>${s.visited.length} / ${Object.keys(D.locations).length}</span></div><p class="hint">故事只在行动时推进。关掉页面不会偷偷消耗食料。</p></aside></main><footer class="footer"><span>非官方同人游戏 · 原文术语 / 可变剧情 · 无服务器、无付费接口</span><span>${count.fields} 个状态字段 · ${count.events} 个节点 · ${count.choices} 个选项</span></footer></div>`;}
function setup(){dialog.innerHTML=`<div class="eyebrow">第一卷 · 青茅山</div><h2>从开窍之后开始</h2><p class="hint">扮演一位古月族人，而不是强制重演方源的人生。原著人物保留身份；你与他们的关系由此局的选择改写。</p><label for="player-name">称呼</label><input id="player-name" maxlength="20" value="古月族人"><label for="grade">资质</label><select id="grade"><option>丙等</option><option>甲等</option><option>乙等</option><option>丁等</option></select><p class="hint">甲等真元更多、恢复更快。丁等的资源压力更大；资质不会因为普通修炼而自动升级。</p><label for="seed">此局种子</label><input id="seed" maxlength="80" value="青茅山"><p class="hint">相同种子与相同行动可重现结果。存档保留随机状态、关系和延迟事件。</p><div class="dialog-footer">${hasGame?btn('取消',{type:'ui',id:'close'}):''}${btn('进入青茅山',{type:'ui',id:'start'},false,'primary')}</div>`;dialog.showModal();}
function saveDialog(){dialog.innerHTML=`<h2>存读档</h2><p class="hint">本浏览器保存三个人工存档与一个自动存档。跨设备请导出 JSON 文件。</p>${['auto','1','2','3'].map(slot=>{const raw=storageGet(KEY+slot);let label='尚无存档';if(raw)try{const t=E.validate(raw);label=`${t.name} · ${when(t.clock)}`;}catch{label='存档损坏，读取不会覆盖当前进度';}return `<div class="save-row"><div><strong>${slot==='auto'?'自动存档':'存档 '+slot}</strong><small>${esc(label)}</small></div><div class="buttons">${slot!=='auto'?btn('保存',{type:'ui',id:'save',slot}):''}${btn('读取',{type:'ui',id:'load',slot},!raw)}</div></div>`;}).join('')}<div class="dialog-footer">${btn('导入存档',{type:'ui',id:'import'})}${btn('关闭',{type:'ui',id:'close'})}</div>`;if(!dialog.open)dialog.showModal();}
function exportSave(){const url=URL.createObjectURL(new Blob([JSON.stringify(s,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`gu-qingmao-day-${E.day(s)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notice('已导出当前进度，包括待触发的后续事件。');}
function ui(c){
 if(c.id==='tab'){tab=c.value;render();}
 else if(c.id==='new'){if(!hasGame||confirm('重新开局会替换自动存档。请先手动存档或导出。继续吗？'))setup();}
 else if(c.id==='start'){s=E.newGame({name:document.getElementById('player-name').value,grade:document.getElementById('grade').value,seed:document.getElementById('seed').value});hasGame=true;autosavePaused=false;initialWarning='';lastSaved=storageGet(KEY+'auto');tab='act';dialog.close();persist(KEY+'auto',true);render();}
 else if(c.id==='saves')saveDialog();else if(c.id==='close')dialog.close();
 else if(c.id==='save'){if(storageGet(KEY+c.slot)&&!confirm('覆盖这个人工存档？'))return;if(persist(KEY+c.slot,true)){notice('存档已保存。');saveDialog();}}
 else if(c.id==='load'){try{const restored=E.validate(storageGet(KEY+c.slot));s=restored;hasGame=true;autosavePaused=false;lastSaved=storageGet(KEY+'auto');dialog.close();persist(KEY+'auto',true);tab='act';render();notice('已读取，人物记忆和后续事件均保留。');}catch(e){notice(e.message);}}
 else if(c.id==='export')exportSave();else if(c.id==='import')document.getElementById('import-file').click();
}
document.addEventListener('click',event=>{const target=event.target.closest('[data-cmd]');if(!target||target.disabled)return;try{const c=JSON.parse(target.dataset.cmd);if(c.type==='ui'){ui(c);return;}const r=E.dispatch(s,c);if(!r.ok){notice(r.message);return;}s=r.state;hasGame=true;if(s.pending||s.combat)tab='act';persist();render();}catch(e){notice('操作未完成：'+e.message);}});
document.addEventListener('change',event=>{if(event.target.dataset.setting){const r=E.dispatch(s,{type:'setting',id:event.target.dataset.setting,value:event.target.checked});if(r.ok){s=r.state;persist();render();}}});
document.getElementById('import-file').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;if(file.size>1500000){notice('存档文件过大，已拒绝导入。');return;}try{const next=E.validate(await file.text());if(!confirm('导入此存档并替换当前自动存档？'))return;s=next;hasGame=true;autosavePaused=false;lastSaved=storageGet(KEY+'auto');dialog.close();persist(KEY+'auto',true);tab='act';render();notice('存档已导入。');}catch(e){notice('导入失败：'+e.message);}});
window.addEventListener('storage',e=>{if(e.key===KEY+'auto'&&e.newValue!==lastSaved){autosavePaused=true;render();}});
const previous=storageGet(KEY+'auto');if(previous){try{s=E.validate(previous);hasGame=true;lastSaved=previous;}catch(e){initialWarning='自动存档未能读取，原数据保留：'+e.message;}}
if(storageGet(OLD)&&!hasGame)initialWarning+=' 检测到旧版存档，已保留；本版不会用新世界观覆盖旧数据。';
render();if(!hasGame)setup();
})();
