/* 专有名词取自 reference/novel；分支、数值与时间表属于游戏改编。 */
(function(root,factory){const d=factory();if(typeof module==='object')module.exports=d;else root.GuContent=d;})(globalThis,()=>{
'use strict';
const chapter=n=>`reference/novel/第1卷：魔性不改/第${n}章.txt`;
const sources=[
 [5,'希望蛊','开窍','资质'],
 [6,'空窍','元海','青铜真元','古月方正','古月博','古月赤练','古月漠尘','悟性','记忆力','力量','敏捷'],
 [7,'青茅山','古月山寨','古月方源','古月师','学堂','蛊室','花酒行者','本命蛊','初阶','中阶','高阶','巅峰'],
 [8,'月光蛊','元石','酒肆'],[10,'古月漠北','古月赤城','炼化','反抗','竹楼'],
 [12,'江牙','青竹酒','客栈','黑皮野猪','米酒'],
 [14,'酒虫','竹林','河滩','石缝','山壁','白家山寨'],
 [23,'月兰花瓣','草人傀儡','草人蛊','月刃','商队','学堂宿舍'],
 [39,'南疆','贾富','知心草','蛮力天牛蛊'],[40,'赌石场','紫金石','癞土蛤蟆']
].flatMap(([n,...terms])=>terms.map(term=>({term,chapter:n,path:chapter(n)})));
const variables={
 health:['身体',100,0,100,'为零则死亡；休息、伤势和战斗共同改变。'],
 essence:['真元',44,0,300,'炼化、修炼、月刃消耗；恢复受资质影响。'],
 hunger:['饥饿',12,0,100,'超过八十后逐小时损伤身体；需要消耗饭菜缓解。'],
 thirst:['口渴',10,0,100,'超过八十后持续损伤身体。'],
 fatigue:['疲劳',5,0,100,'影响修炼、突破、战斗与逃离。'],
 injury:['伤势',0,0,100,'降低修炼和防御；休息能缓慢减轻。'],
 poison:['中毒',0,0,100,'持续损伤身体；疗伤可消除。'],
 spirit:['精神',70,0,100,'影响炼化；冥想、休息恢复。'],
 aptitude:['资质',44,20,99,'决定真元容量、恢复速度和突破难度。'],
 rank:['转数',1,1,5,'改变修炼需求、战斗能力和真元容量；本版至五转。'],
 stage:['阶段',0,0,3,'初阶、中阶、高阶、巅峰；满修为后主动突破。'],
 progress:['修为',0,0,100,'修炼积累；达到一百可以尝试突破。'],
 strength:['力量',14,1,100,'普通攻击与狩猎伤害。'],
 agility:['敏捷',14,1,100,'提高逃离成功率和探索的线索收益。'],
 comprehension:['悟性',14,1,100,'提高修炼所得的修为；听课可以缓慢增长悟性。'],
 memory:['记忆力',14,1,100,'提高听课所得的学识，并影响学堂考核成绩。'],
 will:['意志',16,1,100,'提高突破成功率；准备行装可以缓慢增长意志。'],
 patience:['耐心',16,1,100,'炼化效率与保密时的应对。'],
 combatSkill:['月刃练习',0,0,100,'月刃威力、考核成绩。'],
 refineSkill:['炼化手法',0,0,100,'提高炼化进度，减小反噬。'],
 knowledge:['学识',0,0,100,'影响学堂考核，以及家族盘问时能否用记录解释。'],
 purity:['真元精炼',0,0,100,'酒虫提供；修炼消耗精炼成果，不越过一转适用范围。'],
 stones:['元石',6,0,99999,'购买物资、汲取真元、债务与交易。'],
 reputation:['家族评价',0,-100,100,'影响每周补贴资格与杂务报酬；行动会改变家族评价。'],
 suspicion:['怀疑',0,0,100,'抬高价格并触发家族盘问。'],
 fame:['名声',0,-100,100,'影响交际效果与商队合作。'],
 infamy:['恶名',0,0,100,'记录威胁、侵吞和争斗带来的名声；本版不单独决定阵营。'],
 debt:['欠债',0,0,99999,'到期后影响资助、人际关系与后续追债。'],
 clue:['线索',0,0,100,'追踪酒虫与进入石缝的条件。'],
 secrecy:['隐秘',50,0,100,'决定遗藏是否被旁人盯上。'],
 danger:['山外危险',15,0,100,'提高探索遇敌和寻找食物时中毒的风险。'],
 supply:['物资充足',70,0,100,'影响价格和补货；商队与交货会改变。'],
 readiness:['准备',0,0,100,'降低遭遇战损伤；随战斗消耗。'],
 caravanTrust:['商队信任',0,-100,100,'影响市场价格；履约与违约会改变这份评价。'],
 caravanStock:['商队货物',0,0,50,'记录交出的货物数量，提高此后每周的花瓣补货。'],
 victories:['胜场',0,0,99999,'累计战斗胜利次数，参与之后野猪的强度计算。'],
 studies:['听课次数',0,0,99999,'参与学堂考核计分，至多计入前二十次听课。'],
 hunts:['狩猎次数',0,0,99999,'累计狩猎次数，参与之后野猪的强度计算。'],
 explorations:['探索次数',0,0,99999,'记录探索次数；线索与隐秘由探索行动另行改变。'],
 training:['练习次数',0,0,99999,'每五次练习消耗一具现有草人傀儡，熟练度另行积累。']
};
const goods={food:{name:'饭菜',price:.12,stock:30},water:{name:'清水',price:.04,stock:40},petals:{name:'月兰花瓣',price:.1,stock:80},wine:{name:'青竹酒',price:2,stock:6},riceWine:{name:'米酒',price:.3,stock:20},grass:{name:'知心草',price:.08,stock:20},dummy:{name:'草人傀儡',price:3,stock:3}};
const gus={moon:{name:'月光蛊',chapter:23,food:'petals',amount:2,interval:12,description:'一转蛊。炼化后发出月刃；早晚各喂两片月兰花瓣。知心草可节省花瓣。'},wine:{name:'酒虫',chapter:14,food:'wine',amount:1,interval:96,description:'一转蛊。帮助一转蛊师精炼真元。一坛青竹酒可支撑四日；米酒可作替代。'}};
const locations={
 village:{name:'古月山寨',chapter:7,neighbors:['school','inn','bamboo'],safe:true,description:'家族庇护着蛊师，也审视着每个人的来往。'},
 school:{name:'学堂',chapter:7,neighbors:['village','room','dorm'],safe:true,description:'听课、练习和考核。你在同窗面前的表现会传到家老耳中。'},
 room:{name:'蛊室',chapter:8,neighbors:['school'],safe:true,market:true,description:'江牙在铺子中售卖食料和草人傀儡。'},
 dorm:{name:'学堂宿舍',chapter:23,neighbors:['school'],safe:true,description:'在这里休息、炼化与整理已有线索。'},
 inn:{name:'客栈',chapter:12,neighbors:['village','shop'],safe:true,market:true,description:'猎户和蛊师在此聚散。青竹酒的消息往往先到这里。'},
 shop:{name:'酒肆',chapter:8,neighbors:['inn'],safe:true,market:true,description:'买酒需要元石。多买几坛，也可能引起旁人好奇。'},
 bamboo:{name:'竹林',chapter:14,neighbors:['village','river'],safe:false,description:'青茅山的竹影里有猎物，也可能有循着酒香而来的蛊。'},
 river:{name:'河滩',chapter:14,neighbors:['bamboo','crevice'],safe:false,description:'流水带走气味，也留下足迹。可以取水，或者继续深入。'},
 crevice:{name:'石缝',chapter:14,neighbors:['river','cave'],safe:false,require:[['v.clue','>=',30]],description:'瀑布遮掩着入口。没有线索，贸然寻觅只会绕回原地。'},
 cave:{name:'山壁',chapter:14,neighbors:['crevice'],safe:false,require:[['flags.trail','==','follow']],description:'石缝深处，花酒行者留下的往事等待新的来者。'}
};
const people={
 fangzheng:{name:'古月方正',chapter:6,location:'school',goal:'修炼',trust:0,resources:12},
 fangyuan:{name:'古月方源',chapter:7,location:'bamboo',goal:'遗藏',trust:0,resources:6},
 mobei:{name:'古月漠北',chapter:10,location:'school',goal:'考核',trust:0,resources:18},
 chicheng:{name:'古月赤城',chapter:10,location:'school',goal:'考核',trust:0,resources:18},
 elder:{name:'古月师',chapter:7,location:'school',goal:'家族',trust:0,resources:30},
 jiangya:{name:'江牙',chapter:12,location:'room',goal:'生意',trust:0,resources:20},
 jiafu:{name:'贾富',chapter:39,location:'village',goal:'商队',trust:0,resources:80}
};
const flagKeys=['opening','classmate','purse','patron','debtDue','exam','trail','inheritance','bargain','caravan','order','delivery','rival','audit','ambush','testimony','chapterEnd','rumor'];
// 条件采用受限数据表达式，不执行动态代码。效果键只由本文件声明。
const C=(id,label,text,effects={},extra={})=>({id,label,text,effects,...extra});
const E=(id,title,text,choices,extra={})=>({id,title,text,choices,...extra});
const events=[
 E('opening','开窍之后','希望蛊散去，你成为古月一族的一转蛊师。学堂给了你一只尚未炼化的月光蛊。家族、同窗、山外的机缘，都在你面前。',[
 C('school','先向学堂请教','古月师记住了你的认真。',{add:{knowledge:6,reputation:3},relation:{elder:{trust:5}},set:{opening:'school'}}),
 C('outside','留意山外的消息','你听见有人谈起花酒行者与酒虫。',{add:{clue:12,suspicion:2},set:{opening:'outside'}}),
 C('self','先安排自己的食料','你用一部分元石换来更稳妥的起步。',{add:{stones:-1,patience:2},items:{petals:10,food:2},set:{opening:'self'}})
 ]),
 E('classmate','同窗之间','古月方正请你一起练习。他想知道，你是否愿意将自己琢磨出的技巧告诉他。',[
 C('help','一同练习，不索取报酬','方正记住了这份帮助。',{add:{combatSkill:3},relation:{fangzheng:{trust:18,favor:1}},set:{classmate:'help'}}),
 C('price','以两块元石交换心得','方正付了元石，却不再把这看作交情。',{add:{stones:2},relation:{fangzheng:{trust:-8,fear:2,resources:-2}},set:{classmate:'price'}}),
 C('ignore','保留自己的方法','你省下了时间，也错过了结交的机会。',{add:{progress:6},set:{classmate:'ignore'}})
 ],{locations:['school']}),
 E('purse','地上的钱袋','古月漠北匆匆走过，一只钱袋留在了路旁。附近有人看见你停下，但未必看清了你的动作。',[
 C('return','当面归还','漠北向你道谢，这件事将来或许用得上。',{relation:{mobei:{trust:15,favor:1}},add:{reputation:3},set:{purse:'return'}}),
 C('keep','收进自己的衣袋','你得到元石，也留下了可能被追查的线索。',{add:{stones:6,suspicion:8},relation:{mobei:{anger:8}},set:{purse:'keep'},schedule:[['purseAudit',48]]}),
 C('elder','交给学堂家老','古月师认可你的处理，漠北却觉得此事被人议论。',{relation:{elder:{trust:12},mobei:{trust:-3}},add:{reputation:5},set:{purse:'elder'}})
 ],{locations:['school','village']}),
 E('purseAudit','钱袋的来处','古月漠北询问那日的钱袋。古月师也在旁听。你当时留下的痕迹，并没有随时间消失。',[
 C('return','归还元石并承认','漠北收下元石。疑虑没有全消，但事情没有再扩大。',{add:{stones:-6,suspicion:-4},relation:{mobei:{anger:-5,trust:-3}},set:{rumor:'admitted'}},{requires:[['v.stones','>=',6]]}),
 C('deny','坚持否认','你拒绝说明。漠北决定另找机会与你算账。',{add:{suspicion:15,infamy:4},relation:{mobei:{anger:20,trust:-20}},set:{rumor:'denied'},schedule:[['ambush',48]]}),
 C('debt','承诺以后归还','六块元石成为了一笔真正的债。',{add:{debt:6},relation:{mobei:{anger:5}},set:{rumor:'debt'},schedule:[['debtDue',72]]})
 ]),
 E('patron','家族的资助','家族愿意给你一些帮助。但元石并非没有来处：接受谁的资助，也会让谁对你的选择有所期待。',[
 C('elder','接受学堂的资助','你答应协助学堂。',{add:{stones:5,reputation:5},relation:{elder:{trust:8}},set:{patron:'elder'},schedule:[['patronTask',72]]}),
 C('chi','接受赤之一脉的资助','古月赤城代为转达：这份帮助会被记住。',{add:{stones:8,debt:8},relation:{chicheng:{trust:10}},set:{patron:'chi'},schedule:[['debtDue',120]]}),
 C('none','不接受资助','你仍要自己解决食料与修炼开销。',{add:{will:2},set:{patron:'none'}})
 ],{locations:['school','village']}),
 E('patronTask','资助之后','学堂请你交出一部分月兰花瓣，帮助暂时短缺的学员。兑现承诺会耽搁自己的养蛊。',[
 C('honor','交出八片花瓣','家老愿意继续向你开放任务。',{items:{petals:-8},add:{reputation:8},relation:{elder:{trust:12,favor:1}}},{requires:[['bag.petals','>=',8]]}),
 C('buyout','以两块元石代替','学堂接受了你的安排。',{add:{stones:-2,reputation:3},relation:{elder:{trust:4}}},{requires:[['v.stones','>=',2]]}),
 C('refuse','拒绝这一次请求','家老收回了继续资助你的打算。',{add:{reputation:-12},relation:{elder:{trust:-18}},set:{patron:'broken'}})
 ]),
 E('debtDue','欠下的元石','债主来问你什么时候偿还。拖延已经开始影响旁人对你的看法。',[
 C('pay','偿清欠债','账目结清，此后不再因这笔钱受制于人。',{special:'repay',set:{debtDue:'paid'}}),
 C('delay','再争取三日','利息与怀疑一同增加。',{special:'interest',add:{suspicion:5},set:{debtDue:'delayed'},schedule:[['collection',72]]}),
 C('default','不再认这笔账','债并未消失，你失去了几个人的信任。',{add:{infamy:8,suspicion:12},relation:{chicheng:{trust:-20,anger:15},mobei:{trust:-10,anger:10}},set:{debtDue:'default'},schedule:[['collection',72]]})
 ]),
 E('collection','旧账重提','先前欠下的元石仍在账上。有人愿意让你用劳作抵扣，也有人已经不愿再等。',[
 C('pay','偿还全部欠债','你终于结清了这笔旧账。',{special:'repay',set:{debtDue:'paid'}}),
 C('labor','做杂务抵扣欠债','此后的杂务收入优先偿债；结清后，杂务才重新给你现金报酬。',{set:{debtDue:'labor'},add:{reputation:-3}}),
 C('threat','以实力迫使对方退开','这只能延缓追讨，并不能抹掉欠债。',{add:{infamy:10,suspicion:10},relation:{chicheng:{fear:12,anger:15}},schedule:[['ambush',48]],set:{debtDue:'hostile'}})
 ]),
 E('exam','月刃考核','学堂安排了一次月刃考核。你的练习、学识、准备、疲劳、伤势，以及月光蛊是否炼化且存活，将共同决定表现。',[
 C('enter','按自己的实力参加','考核开始。',{special:'exam',set:{exam:'entered'}},{requires:[['gu.moon.tame','>=',100],['gu.moon.health','>=',1]]}),
 C('favor','请古月漠北帮忙准备','他愿意回报你先前归还钱袋的举动。',{add:{readiness:18,combatSkill:8},relation:{mobei:{favor:-1}},special:'exam',set:{exam:'helped'}},{requires:[['gu.moon.tame','>=',100],['gu.moon.health','>=',1],['npcs.mobei.favor','>=',1]]}),
 C('skip','放弃这次考核','学堂不会等你，但修行的路仍在。',{add:{reputation:-4},set:{exam:'missed'}})
 ],{locations:['school']}),
 E('trail','酒香之后','你在竹林发现一点白光。酒虫似乎已饮了酒，正缓慢飞向河滩。抓住它，跟上它，还是把消息换成眼前的利益？',[
 C('capture','立刻捕捉酒虫','你得到了酒虫，却失去了让它带路的机会。',{gu:'wine',set:{trail:'capture',inheritance:'unfound'},add:{clue:-15},schedule:[['rival',72]]}),
 C('follow','保持距离，让酒虫带路','你记住了它进入的石缝。你还没有得到遗藏。',{set:{trail:'follow'},add:{clue:30,secrecy:-5}}),
 C('report','将消息报告家族','家族封锁了入口，并给你一笔奖励。',{add:{stones:12,reputation:12},relation:{elder:{trust:12}},set:{trail:'report',inheritance:'clan'},schedule:[['clanReward',72]]})
 ],{locations:['bamboo','river'],requires:[['v.clue','>=',25]]}),
 E('inheritance','花酒行者的遗藏','你终于进入石缝深处。酒虫停了下来。这里的发现足以改变你的修行，也足以引来争夺。',[
 C('self','收下遗藏，隐藏入口','元石与酒虫归你，但保密需要付出代价。',{gu:'wine',add:{stones:16,knowledge:8,secrecy:-10},set:{inheritance:'self'},schedule:[['rival',48],['audit',120]]}),
 C('share','请古月方源共同处理','你将线索告诉方源。他收下酒虫，与你分了元石，但不会无条件相信你。',{add:{stones:10,knowledge:12},relation:{fangyuan:{trust:16,favor:1}},set:{inheritance:'shared'},schedule:[['bargain',72]]}),
 C('clan','把入口交给家族','家族接管了遗藏，今后的好处也要按家族的规矩来。',{add:{stones:8,reputation:15},relation:{elder:{trust:15}},set:{inheritance:'clan'},schedule:[['clanReward',72]]})
 ],{locations:['cave'],requires:[['flags.trail','==','follow'],['flags.inheritance','==','']]}),
 E('rival','有人循迹而来','古月方源来问你近日的行踪。他没有说破，但目光已经落在你对酒水和食料的需求上。',[
 C('deal','拿出五块元石，谈一次交易','他接受这一笔利益交换，而非一份交情保证。',{add:{stones:-5},relation:{fangyuan:{trust:8}},set:{rival:'deal'},schedule:[['bargain',72]]},{requires:[['v.stones','>=',5]]}),
 C('hide','维持先前的说辞','你试图不让自己的前后说法出现矛盾。',{special:'conceal',set:{rival:'hide'}}),
 C('challenge','拒绝谈判，准备争夺','你们之间的冲突不再只是猜测。',{relation:{fangyuan:{anger:22,trust:-15}},add:{danger:10},set:{rival:'hostile'},schedule:[['ambush',48]]})
 ]),
 E('bargain','利益交换','古月方源带来一则食料消息。他愿意给你帮助，但要求你暂时不要向家族谈及彼此的交易。',[
 C('honor','接受条件，保守秘密','你得到了物资，也承担了沉默的代价。',{items:{petals:12,wine:1},relation:{fangyuan:{trust:10}},set:{bargain:'kept'},schedule:[['audit',72]]}),
 C('report','把交易告诉学堂家老','你换取家族的信任，却破坏了另一份约定。',{add:{reputation:8},relation:{elder:{trust:10},fangyuan:{trust:-25,anger:20}},set:{bargain:'betrayed'},schedule:[['ambush',72]]}),
 C('decline','不参加这次交易','双方没有新的承诺。',{set:{bargain:'declined'}})
 ]),
 E('clanReward','家族的安排','你交出的消息已经有了结果。家族让你在食料和修行帮助之间作出选择。',[
 C('supplies','领取食料','这些花瓣能减轻养蛊的负担。',{items:{petals:24,food:5},add:{reputation:3}}),
 C('teaching','请求指点炼化','学堂家老指出了你运用真元时的问题。',{add:{refineSkill:12,knowledge:8},relation:{elder:{trust:5}}}),
 C('cash','换成元石','你把家族的奖励变成了眼下可支配的资源。',{add:{stones:6}})
 ]),
 E('caravan','商队到来','贾富的商队进入古月山寨。货物多了，但青竹酒也会被大量收购。原来稳定的养蛊开销，开始发生变化。',[
 C('reserve','提前订下三坛青竹酒','你支付四块元石的订金；两日后可提货，也可能转给商队。',{add:{stones:-4,caravanTrust:5},set:{caravan:'reserve'},schedule:[['order',48]]},{requires:[['v.stones','>=',4]]}),
 C('contract','替商队收集二十片月兰花瓣','你收下一块元石预付款。三日后需要交货。',{add:{stones:1},set:{caravan:'contract'},schedule:[['delivery',72]]}),
 C('independent','只按自己的需要买卖','你没有承担订单，但也没有锁定价格。',{set:{caravan:'independent'}})
 ],{locations:['village','inn','shop','room']}),
 E('order','预订的青竹酒','你预订的三坛酒送到了。商队愿意出价收购，留下养蛊还是转手，要由你决定。',[
 C('keep','留下三坛酒','原来的订金已付清，三坛酒进入行囊。',{items:{wine:3},set:{order:'kept'}}),
 C('sell','以七块元石转给商队','你赚了差价，却要重新面对食料短缺。',{add:{stones:7,caravanTrust:5},set:{order:'sold'}})
 ]),
 E('delivery','到了交货的时候','商队来取月兰花瓣。此前收下的预付款，已经让这件事不再只是一次随口应允。',[
 C('deliver','交出二十片花瓣','商队付清余款。下一次交易，他们愿意给你更好的条件。',{items:{petals:-20},add:{stones:3,caravanTrust:15,caravanStock:20,supply:8},relation:{jiafu:{trust:12}},set:{delivery:'done'}} ,{requires:[['bag.petals','>=',20]]}),
 C('refund','退还一块元石','你没能交货，但没有侵吞订金。',{add:{stones:-1,caravanTrust:-3},set:{delivery:'refunded'}},{requires:[['v.stones','>=',1]]}),
 C('steal','留下订金，拒绝交货','商队记住了这次违约，后续交易不再照顾你。',{add:{caravanTrust:-25,suspicion:6},relation:{jiafu:{trust:-20,anger:10}},set:{delivery:'default'},schedule:[['merchantAfter',48]]})
 ]),
 E('merchantAfter','商队的回应','你之前没有交货。商队停止给你留货，也拒绝按旧价交易。',[
 C('repair','支付两块元石赔偿','商队不再追究旧账，但信任仍需重建。',{add:{stones:-2,caravanTrust:10},relation:{jiafu:{anger:-8}},set:{delivery:'repaired'}},{requires:[['v.stones','>=',2]]}),
 C('accept','接受失去这条交易关系','你往后只能从别处设法取得物资。',{add:{supply:-8},set:{delivery:'closed'}})
 ]),
 E('audit','家族盘问','家老问起山外的行踪、元石的来处，以及你与古月方源的交易。先前的选择决定了你能拿出怎样的说法。',[
 C('evidence','用听课记录与往来账目说明','你的准备让家老愿意接受解释。',{add:{suspicion:-20},relation:{elder:{trust:6}},set:{audit:'cleared'}},{requires:[['v.knowledge','>=',18],['npcs.elder.trust','>=',5]]}),
 C('confess','交代遗藏与交易','怀疑有所消退，但方源不会忘记秘密外泄。',{add:{suspicion:-10,reputation:3,secrecy:-25},relation:{fangyuan:{trust:-15,anger:12}},set:{audit:'confessed'},schedule:[['testimony',48]]}),
 C('silent','拒绝作出解释','家族对你的活动加强了留意。',{add:{suspicion:15,reputation:-8},set:{audit:'silent'},schedule:[['ambush',48]]})
 ]),
 E('testimony','谁愿意作证','盘问过后，事情并未立刻平息。你需要有人证明你所说的部分经过。',[
 C('friend','请古月方正作证','他记得你曾经帮过他，愿意出面说明。',{relation:{fangzheng:{favor:-1}},add:{suspicion:-15,reputation:5},set:{testimony:'friend'}},{requires:[['npcs.fangzheng.trust','>=',12],['npcs.fangzheng.favor','>=',1]]}),
 C('pay','支付三块元石补偿家族的损失','这不能买来完全的信任，但足以让事情暂时结束。',{add:{stones:-3,suspicion:-8},set:{testimony:'paid'}},{requires:[['v.stones','>=',3]]}),
 C('alone','独自承担后果','你保住了元石，却被暂停了一部分家族待遇。',{add:{reputation:-12},set:{testimony:'alone'}})
 ]),
 E('ambush','归途中','有人在竹影里拦下你。这不是无缘无故的恶意；你曾经的隐瞒、威胁或违约，已经传到了这里。',[
 C('friend','向古月方正求援','他替你挡下了这次冲突。先前的帮助，终于在另一处兑现。',{relation:{fangzheng:{favor:-1,trust:4}},add:{readiness:10},set:{ambush:'rescued'}},{requires:[['npcs.fangzheng.trust','>=',12],['npcs.fangzheng.favor','>=',1]]}),
 C('fight','准备动手','你必须靠已有的蛊虫与实力脱身。',{combat:'rival',set:{ambush:'fought'}}),
 C('pay','交出四块元石换取退路','对方暂时让开了道路。',{add:{stones:-4,infamy:-2},set:{ambush:'paid'}},{requires:[['v.stones','>=',4]]}),
 C('escape','寻找空隙逃走','你试着从竹影中脱身。',{special:'escapeEvent',set:{ambush:'escaped'}})
 ]),
 E('shortage','养蛊的开销','最近物资不如从前充足。你身上的元石也在减少。放任蛊虫饥饿，可能会失去它。',[
 C('borrow','向古月赤城借三块元石','他给了元石，三日后会来询问偿还。',{add:{stones:3,debt:3},relation:{chicheng:{trust:2}},schedule:[['debtDue',72]]}),
 C('work','多做一些杂务','你换到了一些饭菜，疲劳也增加了。',{add:{fatigue:10},items:{food:3,water:3}}),
 C('hold','不再借钱，自己安排','你决定减少其他开支，先维持养蛊。',{add:{patience:1}})
 ],{requires:[['v.stones','<=',2]]}),
 E('chapterEnd','仍未走完的路','回看这些日子，你留下的不只有修为。有人愿意帮你，有人等待你还债，还有人记得你没守住的秘密。故事没有在这里结束。',[
 C('stay','继续留在古月山寨','你继续修炼、经营关系，也继续面对旧事的后果。',{set:{chapterEnd:'stay'},add:{readiness:5}}),
 C('outside','把更多精力放在山外','你打算继续探索青茅山。',{set:{chapterEnd:'outside'},add:{danger:5,clue:5}}),
 C('trade','争取商队的合作','你开始主动修补与商队的关系。',{set:{chapterEnd:'trade'},add:{caravanTrust:3}})
 ])
];
const actions=[
 {id:'cultivate',name:'修炼',hours:2,hint:'消耗真元，温养空窍；疲劳与伤势会降低成果。'},
 {id:'study',name:'听课',hours:2,locations:['school'],hint:'学识、悟性和记忆力增长；影响考核及家族盘问。'},
 {id:'train',name:'练习月刃',hours:2,locations:['school','dorm','bamboo'],hint:'需要炼化月光蛊；草人傀儡提高练习效率。'},
 {id:'work',name:'做些杂务',hours:2,locations:['village','school','inn'],hint:'获得少量元石；劳作偿债时优先抵扣欠债。'},
 {id:'meditate',name:'冥想',hours:2,hint:'恢复精神，增长耐心；危险地点效果较差。'},
 {id:'explore',name:'探索',hours:3,locations:['bamboo','river','crevice','cave'],hint:'积累线索，但会消耗体力、提高暴露风险。'},
 {id:'lure',name:'以酒引蛊',hours:2,locations:['bamboo','river'],hint:'消耗一坛青竹酒；雨天效果更差。'},
 {id:'hunt',name:'狩猎',hours:2,locations:['bamboo','river'],hint:'进入可逐回合选择的战斗，胜利后获得食物。'},
 {id:'forage',name:'寻找食物',hours:2,locations:['bamboo','river'],hint:'获得食物，也有受伤、中毒的风险。'},
 {id:'water',name:'取水',hours:1,locations:['river'],hint:'获得三份清水。'},
 {id:'rest',name:'休息',hours:8,locations:['dorm','inn','village'],hint:'恢复身体、精神，降低疲劳；养蛊和饥渴仍会继续。'},
 {id:'heal',name:'疗伤',hours:4,locations:['dorm','inn','school'],hint:'花费一块元石处理伤势与中毒。'},
 {id:'prepare',name:'准备行装',hours:2,hint:'提高准备程度，下次战斗会更从容。'},
 {id:'absorb',name:'汲取元石',hours:1,hint:'消耗一块元石，快速补充真元。'},
 {id:'breakthrough',name:'突破',hours:4,hint:'修为满后尝试；失败会受伤。本版开放一至五转。'}
];
return {VERSION:2,sources,variables,goods,gus,locations,people,flagKeys,events,actions,stages:['初阶','中阶','高阶','巅峰'],grades:{'甲等':88,'乙等':66,'丙等':44,'丁等':28},weather:['晴','雨','雾'],chapter};
});
