/* 0.4 immersive presentation adapter. It only emits existing data-cmd commands; engine.js remains the rule authority. */
(()=>{
'use strict';
const D=window.GuContent,E=window.GuEngine,N=window.GuNarrative,KEY='gu_qingmao_v2_auto';
if(!D||!E||!N)return;
const app=document.getElementById('app'),dialog=document.getElementById('dialog'),notice=document.getElementById('notice');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>Number(x).toLocaleString('zh-CN',{maximumFractionDigits:1});
const enc=x=>esc(JSON.stringify(x));
const button=(label,c,disabled=false,cls='')=>`<button class="${cls}" data-cmd="${enc(c)}" ${disabled?'disabled':''}>${label}</button>`;
function state(){try{const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw):null;}catch{return null;}}
const day=s=>Math.floor(s.clock/24)+1;
function toast(text){if(!notice)return;notice.textContent=text;notice.classList.add('visible');setTimeout(()=>notice.classList.remove('visible'),3800);}
function tab(){const t=document.querySelector('.tabbar button.selected')?.textContent||'行止';return t.includes('青茅')?'map':t.includes('蛊虫')?'gu':t.includes('人物')?'people':t.includes('买卖')?'trade':t.includes('往事')?'history':t.includes('原文')?'sources':'act';}
function focal(s){if(s.pending){const e=E.events[s.pending.id],text=(e?.title||'')+' '+(e?.text||'');for(const[id,p]of Object.entries(D.people))if(text.includes(p.name))return id;}return Object.entries(D.people).find(([id,p])=>p.location===s.location&&(id!=='jiafu'||day(s)>=12))?.[0]||null;}
function bodyState(s){if(s.v.health<35||s.v.injury>35)return['伤','warn'];if(s.v.fatigue>75)return['倦','warn'];if(s.v.hunger>70||s.v.thirst>70)return['饥','warn'];return['安',''];}
function hud(s){const loc=N.scene(s.location),cap=E.capacity(s),cond=bodyState(s);return `<div class="v4-hud"><div class="v4-hud-left"><div class="v4-location"><span class="v4-location-mark">${esc(loc.glyph)}</span><div><strong>${esc(loc.title)}</strong><span>${esc(loc.kicker)}</span></div></div><div class="v4-time"><b>${day(s)}</b>日 · ${String(s.clock%24).padStart(2,'0')}:00 · ${esc(s.weather)}</div></div><div class="v4-hud-right"><span class="v4-rank">${['','一','二','三','四','五'][s.v.rank]}转${D.stages[s.v.stage]}</span><div class="v4-essence"><label><span>真元</span><span>${fmt(s.v.essence)}/${fmt(cap)}</span></label><div class="v4-essence-track"><i style="width:${Math.max(0,Math.min(100,s.v.essence/cap*100))}%"></i></div></div><span class="v4-stones">元石 <b>${fmt(s.v.stones)}</b></span><span class="v4-condition ${cond[1]}">${cond[0]}</span></div></div>`;}
const nav=[['act','行','行止'],['map','山','地图'],['gu','蛊','蛊虫'],['people','人','人物'],['trade','市','买卖'],['history','忆','往事']];
function dock(active){return `<nav class="v4-dock" aria-label="主要菜单">${nav.map(([id,g,n])=>`<button data-v4-tab="${id}" class="${id===active?'active':''}"><b>${g}</b><small>${n}</small></button>`).join('')}<button data-v4-graph><b>因</b><small>因果</small></button><button data-v4-menu class="v4-menu"><b>☰</b><small>菜单</small></button></nav>`;}
function world(s){const v=N.scene(s.location);return `<div class="v4-world tone-${esc(v.tone)}"><div class="sun"></div><div class="far-range"></div><div class="near-range"></div><div class="bamboo"></div><div class="water"></div><div class="lanterns"></div><div class="fog"></div></div><div class="v4-world-label"><div class="eyebrow">${esc(v.kicker)}</div><h1>${esc(v.title)}</h1><p>${esc(v.caption)}</p></div>`;}
const player=dim=>`<div class="v4-player ${dim?'dim':''}"><img src="assets/portraits/player.svg" alt="你的角色立绘"></div>`;
function npc(id){if(!id)return'';const p=N.portrait(id);return `<div class="v4-npc stance-${esc(p.stance)}"><div class="npc-aura"></div><div class="npc-head"></div><div class="npc-body"></div><div class="npc-glyph">${esc(p.glyph)}</div><div class="npc-name"><strong>${esc(p.role)}</strong><small>${esc(p.subtitle)}</small></div></div>`;}
function reqs(req){return(req||[]).map(([p,o,v])=>`${p}${o}${v}`).join('；');}
function preview(c){const f=c.effects||{},a=[];for(const[k,v]of Object.entries(f.add||{}))if(D.variables[k])a.push(`${D.variables[k][0]} ${v>=0?'+':''}${v}`);for(const[k,v]of Object.entries(f.items||{}))if(D.goods[k])a.push(`${D.goods[k].name} ${v>=0?'+':''}${v}`);for(const[id,vals]of Object.entries(f.relation||{}))for(const[k,v]of Object.entries(vals))if(['trust','anger','favor'].includes(k))a.push(`${D.people[id].name}${{trust:'信任',anger:'敌意',favor:'人情'}[k]} ${v>=0?'+':''}${v}`);if(f.schedule)a.push('会留下后续');if(f.combat)a.push('进入交锋');return a.slice(0,4).join(' · ');}
function pending(s){const e=E.events[s.pending.id],pid=focal(s),speaker=pid?N.portrait(pid).role:e.title;return `<section class="v4-play">${world(s)}${player(true)}${npc(pid)}<div class="v4-dialogue"><span class="v4-speaker">${esc(speaker)}</span>${s.pending.source?`<span class="origin">缘起：${esc(s.pending.source)}</span>`:''}<h2>${esc(e.title)}</h2><p class="narration">${esc(e.text)}</p><div class="v4-choices">${e.choices.map((c,i)=>{const reason=E.choiceReason(s,c),p=preview(c);return `<button class="v4-choice" data-cmd="${enc({type:'choice',id:c.id})}" ${reason?'disabled':''}><span class="num">0${i+1}</span><span><strong>${esc(c.label)}</strong>${p?`<small>${esc(p)}</small>`:''}${c.requires?`<small>条件：${esc(reqs(c.requires))}</small>`:''}${reason?`<em>${esc(reason)}</em>`:''}</span></button>`;}).join('')}</div></div></section>`;}
function combat(s){const c=s.combat,moves=[['strike','攻','近身攻击','不耗真元'],['moon','月','催动月光蛊','消耗 8 真元'],['guard','守','防守','减轻本回合伤害'],['escape','退','设法逃离','失败会受到攻击']];return `<section class="v4-play">${world(s)}${player(false)}<div class="v4-enemy" data-glyph="${esc(c.kind==='boar'?'豕':'敌')}"></div><div class="v4-combat-panel"><div class="v4-combat-head"><h2>${esc(c.name)} · 第 ${c.round+1} 回合</h2><span class="hint">身体 ${fmt(s.v.health)} · 真元 ${fmt(s.v.essence)}</span></div><div class="v4-enemy-health"><i style="width:${Math.max(0,c.health/c.maxHealth*100)}%"></i></div><div class="v4-combat-actions">${moves.map(([id,g,n,h])=>{const off=id==='moon'&&(s.v.essence<8||!s.gu.moon||s.gu.moon.tame<100||s.gu.moon.health<=0);return `<button data-cmd="${enc({type:'combat',id})}" ${off?'disabled':''}><strong>${g} · ${n}</strong><small>${h}</small></button>`;}).join('')}</div></div></section>`;}
function goal(s){if(s.gu.moon.tame<100)return'先把月光蛊真正炼化。真元不足时，可汲取元石或休息。';if(s.flags.trail==='')return'留在学堂积累底子，或带着青竹酒去竹林寻找另一条路。';if(s.flags.trail==='follow'&&s.flags.inheritance==='')return'酒虫的踪迹通向石缝深处。继续走，代价也会跟着变大。';return'你的选择已经改变了旁人。下一件事不会只由剧情进度决定。';}
function free(s){const loc=D.locations[s.location],acts=D.actions.filter(a=>!a.locations||a.locations.includes(s.location));return `<section class="v4-play">${world(s)}${player(false)}<div class="v4-quiet-line">${esc(goal(s))}</div><div class="v4-freeplay"><div class="v4-freeplay-head"><h2>你要做什么？</h2><span>${loc.safe?'山寨之内':'山寨之外'} · 行动会推进时间</span></div><div class="v4-actions">${acts.map(a=>{const r=E.actionReason(s,a.id);return `<button class="v4-action" data-cmd="${enc({type:'action',id:a.id})}" ${r?'disabled':''}><span class="sigil">${esc(a.name[0])}</span><span><strong>${esc(a.name)}</strong><small>${esc(r||a.hint)}</small></span><i>${a.hours}h</i></button>`;}).join('')}</div><div class="v4-travel">${loc.neighbors.map(id=>`<button data-cmd="${enc({type:'travel',id})}" ${!E.meets(s,D.locations[id].require)?'disabled':''}>前往 ${esc(D.locations[id].name)} →</button>`).join('')}</div></div></section>`;}
function act(s){if(!s.alive)return `<section class="v4-play">${world(s)}${player(true)}<div class="v4-dialogue"><span class="v4-speaker">此局已终</span><h2>人间一场，行至于此。</h2><p class="narration">你留下的往事仍可翻阅。另一条路，要从下一次开局开始。</p>${button('重新开局',{type:'ui',id:'new'},false,'primary')}</div></section>`;return s.pending?pending(s):s.combat?combat(s):free(s);}
function pageBanner(id){const a={map:['青茅山','你真正走过的路。'],gu:['蛊虫','炼蛊、用蛊、养蛊。力量也意味着代价。'],people:['人物','他们记得你做过什么。'],trade:['买卖','元石既是钱，也是修行资源。'],history:['往事','已经做出的选择，与尚未找上门的后果。'],sources:['原文','专有名词来自仓库原文；新的命运属于这局游戏。']}[id]||['青茅山',''];return `<div class="v4-page-banner"><div><div class="eyebrow">IMMERSIVE ARCHIVE</div><h1>${a[0]}</h1></div><p>${a[1]}</p></div>`;}
function page(stage,s,id){stage.classList.add('v4-page-stage');if(!stage.querySelector(':scope > .v4-page-banner'))stage.insertAdjacentHTML('afterbegin',pageBanner(id));if(id==='people'){const cards=[...stage.querySelectorAll('.cards > .card')],ids=Object.keys(D.people);cards.forEach((card,i)=>{const bar=card.querySelector('.buttons');if(bar&&!card.querySelector('[data-v4-person]')){const b=document.createElement('button');b.textContent='选择话题';b.dataset.v4Person=ids[i];bar.prepend(b);}});}}
function graph(s){const seen=new Set(Object.keys(s.seen||{})),queued=new Set((s.queue||[]).map(q=>q.id)),pendingId=s.pending?.id||'';const lanes=new Map(N.laneOrder.map(x=>[x,[]]));for(const e of D.events){const l=N.lane(e.id);if(!lanes.has(l))lanes.set(l,[]);lanes.get(l).push(e);}return `<div class="graph-dialog"><div class="eyebrow">STORY GRAPH</div><h2>因果图</h2><p class="hint">绿色已发生，金色正在处理，蓝色已经进入未来队列。</p><div class="story-graph">${[...lanes].filter(([,x])=>x.length).map(([l,x])=>`<section class="graph-lane"><h3>${esc(l)}</h3>${x.map(e=>`<article class="graph-node ${e.id===pendingId?'pending':queued.has(e.id)?'queued':seen.has(e.id)?'seen':'future'}"><div class="node-dot"></div><small>${esc(e.id)}</small><strong>${esc(e.title)}</strong><p>${e.choices.length} 个选择</p></article>`).join('')}</section>`).join('')}</div><div class="dialog-footer"><button data-v4-close>关闭</button></div></div>`;}
function topic(s,id){const p=D.people[id],n=s.npcs[id],m=N.portrait(id),here=p.location===s.location&&(id!=='jiafu'||day(s)>=12);return `<div class="topic-dialog"><div class="topic-portrait"><span>${esc(m.glyph)}</span></div><div><div class="eyebrow">你想和他谈什么？</div><h2>${esc(p.name)}</h2><p class="hint">${n.favor>0?'欠你人情':'没有未还人情'} · ${n.anger>20?'明显戒备':n.trust>25?'较为信任':'态度未明'}</p></div></div><div class="topic-list">${N.topicsFor(id).map(t=>{const ok=(t.requires||[]).every(([path,o,v])=>{let x=s;for(const k of path.split('.'))x=x?.[k];return o==='>='?x>=v:o==='<='?x<=v:o==='=='?x===v:o==='!='?x!==v:false;});return `<button class="topic-choice" data-v4-topic="${esc(id)}:${esc(t.id)}" ${!here||!ok?'disabled':''}><strong>${esc(t.label)}</strong><small>${esc(t.prompt)}</small>${!ok?'<em>这个话题现在还开不了口</em>':''}</button>`;}).join('')}</div><div class="dialog-footer"><button data-v4-close>关闭</button></div>`;}
function menu(s){const c=bodyState(s)[0];return `<div class="v4-menu-panel"><div class="eyebrow">CHARACTER · SYSTEM</div><h2>${esc(s.name)}</h2><p class="hint">精确数字被收进这里。主画面只保留角色此刻真正会感受到的信息。</p><div class="v4-menu-grid"><div><span>境界</span><b>${['','一','二','三','四','五'][s.v.rank]}转${D.stages[s.v.stage]}</b></div><div><span>身体状态</span><b>${c}</b></div><div><span>资质 / 修为</span><b>${fmt(s.v.aptitude)}% / ${fmt(s.v.progress)}</b></div><div><span>元石 / 欠债</span><b>${fmt(s.v.stones)} / ${fmt(s.v.debt)}</b></div><div><span>家族评价 / 怀疑</span><b>${fmt(s.v.reputation)} / ${fmt(s.v.suspicion)}</b></div><div><span>伤势 / 疲劳</span><b>${fmt(s.v.injury)} / ${fmt(s.v.fatigue)}</b></div></div><div class="v4-menu-actions">${button('存读档',{type:'ui',id:'saves'})}${button('导出存档',{type:'ui',id:'export'})}${button('重新开局',{type:'ui',id:'new'})}<button data-v4-copy>复制试玩状态</button><button data-v4-close>关闭</button></div><div class="v4-feedback">复制试玩状态后直接粘贴给我，可以精确定位你在哪个剧情状态下觉得体验不好。</div><details><summary>查看全部规则变量</summary><div class="v4-variable-list">${Object.entries(D.variables).map(([k,v])=>`<div class="v4-variable-row"><span>${esc(v[0])}</span><b>${fmt(s.v[k])}</b></div>`).join('')}</div></details></div>`;}
function copy(s){const t=[`蛊真人青茅山 UI 0.4`,`第${day(s)}日 ${String(s.clock%24).padStart(2,'0')}:00`,`地点：${D.locations[s.location].name}`,`境界：${['','一','二','三','四','五'][s.v.rank]}转${D.stages[s.v.stage]}`,`当前：${s.pending?E.events[s.pending.id]?.title||s.pending.id:s.combat?'战斗 '+s.combat.name:'自由行动'}`,`元石：${s.v.stones}；真元：${s.v.essence}/${E.capacity(s)}`,`伤势：${s.v.injury}；疲劳：${s.v.fatigue}；怀疑：${s.v.suspicion}`,`未了事项：${s.queue.length}`,`种子：${s.seed}`].join('\n');navigator.clipboard?.writeText(t).then(()=>toast('试玩状态已复制。')).catch(()=>toast(t));}
function setup(){if(!dialog.open||dialog.classList.contains('v4-setup-dialog')||!dialog.querySelector('#player-name'))return;dialog.classList.add('v4-setup-dialog');const wrap=document.createElement('div');wrap.className='v4-setup-form';while(dialog.firstChild)wrap.appendChild(dialog.firstChild);dialog.innerHTML=`<section class="v4-setup-cinematic"><div class="v4-setup-range"></div><div class="v4-setup-copy"><div class="eyebrow">南疆 · 十万大山</div><h1>今天，是开窍大典。</h1><p>青茅山上，古月一族已经繁衍数百年。资质会决定别人怎样看你、家族愿意给你多少资源，却不会替你决定以后走哪条路。</p></div><img class="v4-setup-player" src="assets/portraits/player.svg" alt="你的角色立绘"><div class="v4-intro-ribbon"><span>蛊师有九转</span><span>元石也是修行资源</span><span>选择会留下后果</span></div></section>`;dialog.appendChild(wrap);}
function chrome(s){document.body.classList.add('immersive-v4');if(!s){document.querySelectorAll('.v4-hud,.v4-dock').forEach(x=>x.remove());delete document.body.dataset.v4Chrome;return;}const active=tab(),key=[s.clock,s.location,s.v.rank,s.v.stage,s.v.essence,s.v.stones,s.v.health,s.v.injury,active].join(':');if(document.body.dataset.v4Chrome===key&&document.querySelector('.v4-hud')&&document.querySelector('.v4-dock'))return;document.body.dataset.v4Chrome=key;document.querySelectorAll('.v4-hud,.v4-dock').forEach(x=>x.remove());document.body.insertAdjacentHTML('beforeend',hud(s)+dock(active));}
function enhance(){setup();const s=state();chrome(s);const stage=document.querySelector('.stage');if(!s||!stage)return;const active=tab(),key=[active,s.clock,s.location,s.pending?.id||'',s.combat?.round??'',s.ledger?.actions||0].join(':');if(stage.dataset.v4===key)return;stage.dataset.v4=key;stage.classList.remove('v4-play','v4-page-stage','legacy-vn','legacy-combat');if(active==='act'){stage.classList.add('v4-play');stage.innerHTML=act(s);}else page(stage,s,active);}
let queued=false;const observer=new MutationObserver(()=>{if(queued)return;queued=true;queueMicrotask(()=>{queued=false;enhance();});});observer.observe(document.body,{childList:true,subtree:true});
document.addEventListener('click',ev=>{const n=ev.target.closest('[data-v4-tab]');if(n){const label={act:'行止',map:'青茅山',gu:'蛊虫',people:'人物',trade:'买卖',history:'往事'}[n.dataset.v4Tab];[...document.querySelectorAll('.tabbar button')].find(b=>b.textContent.includes(label))?.click();return;}if(ev.target.closest('[data-v4-menu]')){const s=state();if(s){dialog.innerHTML=menu(s);dialog.showModal();}return;}if(ev.target.closest('[data-v4-graph]')){const s=state();if(s){dialog.innerHTML=graph(s);dialog.showModal();}return;}const p=ev.target.closest('[data-v4-person]');if(p){const s=state();if(s){dialog.innerHTML=topic(s,p.dataset.v4Person);dialog.showModal();}return;}const t=ev.target.closest('[data-v4-topic]');if(t){const [id,tid]=t.dataset.v4Topic.split(':'),meta=N.topicsFor(id).find(x=>x.id===tid);dialog.close();const cards=[...document.querySelectorAll('.stage .cards > .card')],i=Object.keys(D.people).indexOf(id),chat=cards[i]?.querySelector('button[data-cmd]');if(chat){chat.click();toast(`${D.people[id].name} · ${meta?.label||'交谈'}：${meta?.prompt||''}`);}return;}if(ev.target.closest('[data-v4-copy]')){const s=state();if(s)copy(s);return;}if(ev.target.closest('[data-v4-close]'))dialog.close();});
enhance();
})();
