/* Additive visual-novel layer. It never mutates game state directly. */
(()=>{
'use strict';
const D=window.GuContent,N=window.GuNarrative,KEY='gu_qingmao_v2_auto';
if(!D||!N)return;
const app=document.getElementById('app'),dialog=document.getElementById('dialog'),notice=document.getElementById('notice');
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=x=>Number(x).toLocaleString('zh-CN',{maximumFractionDigits:1});
function state(){try{const raw=localStorage.getItem(KEY);return raw?JSON.parse(raw):null;}catch{return null;}}
function showNotice(text){if(!notice)return;notice.textContent=text;notice.classList.add('visible');setTimeout(()=>notice.classList.remove('visible'),4200);}
function focal(s){if(!s?.pending)return null;const e=D.events.find(x=>x.id===s.pending.id);if(!e)return null;const text=e.title+' '+e.text;for(const[id,p]of Object.entries(D.people))if(text.includes(p.name))return id;return Object.entries(D.people).find(([id,p])=>p.location===s.location&&(id!=='jiafu'||Math.floor(s.clock/24)+1>=12))?.[0]||null;}
function portrait(id){if(!id)return '';const p=N.portrait(id);return `<div class="vn-portrait right stance-${esc(p.stance)}"><div class="portrait-aura"></div><div class="portrait-head"></div><div class="portrait-body"></div><div class="portrait-glyph">${esc(p.glyph)}</div><div class="portrait-tag"><strong>${esc(p.role)}</strong><span>${esc(p.subtitle)}</span></div></div>`;}
function scene(s,person=null){const v=N.scene(s.location);return `<div class="scene-art tone-${esc(v.tone)} vn-visual-banner"><div class="sun-disc"></div><div class="mountains far"></div><div class="mountains near"></div><div class="bamboo-layer"></div><div class="mist"></div><div class="scene-mark">${esc(v.glyph)}</div>${portrait(person)}<div class="scene-caption"><span>${esc(v.kicker)}</span><strong>${esc(v.title)}</strong></div></div>`;}
function graphHTML(s){const seen=new Set(Object.keys(s.seen||{})),queued=new Set((s.queue||[]).map(q=>q.id)),pending=s.pending?.id||'';const lanes=new Map(N.laneOrder.map(x=>[x,[]]));for(const e of D.events){const lane=N.lane(e.id);if(!lanes.has(lane))lanes.set(lane,[]);lanes.get(lane).push(e);}const links=e=>{const ids=[];for(const c of e.choices||[])for(const entry of c.effects?.schedule||[])if(!ids.includes(entry[0]))ids.push(entry[0]);return ids;};return `<div class="graph-dialog"><div class="eyebrow">STORY GRAPH · 当前存档</div><h2>因果图</h2><p class="hint">节点来自真实剧情数据；箭头来自选择中的延迟 <code>schedule</code>。绿色已发生，金色正在处理，蓝色已经排队。</p><div class="story-graph">${[...lanes.entries()].filter(([,xs])=>xs.length).map(([name,xs])=>`<section class="graph-lane"><h3>${esc(name)}</h3>${xs.map(e=>{const status=e.id===pending?'pending':queued.has(e.id)?'queued':seen.has(e.id)?'seen':'future',out=links(e);return `<article class="graph-node ${status}"><div class="node-dot"></div><small>${esc(e.id)}</small><strong>${esc(e.title)}</strong><p>${e.choices.length} 个选择${e.locations?` · ${e.locations.map(k=>esc(D.locations[k].name)).join('/')}`:''}</p>${out.length?`<div class="node-links">→ ${out.map(id=>esc(D.events.find(x=>x.id===id)?.title||id)).join(' · ')}</div>`:''}</article>`;}).join('')}</section>`).join('')}</div><div class="dialog-footer"><button data-v3-close>关闭</button></div></div>`;}
function topicHTML(s,id){const p=D.people[id],n=s.npcs[id],meta=N.portrait(id),day=Math.floor(s.clock/24)+1,here=p.location===s.location&&(id!=='jiafu'||day>=12);return `<div class="topic-dialog"><div class="topic-portrait stance-${esc(meta.stance)}"><span>${esc(meta.glyph)}</span></div><div><div class="eyebrow">DIALOGUE TOPICS</div><h2>${esc(p.name)}</h2><p class="hint">${esc(meta.subtitle)} · 信任 ${fmt(n.trust)} · 敌意 ${fmt(n.anger)} · 人情 ${fmt(n.favor)}</p></div></div><div class="topic-list">${N.topicsFor(id).map(t=>{const ok=(t.requires||[]).every(([path,op,val])=>{let x=s;for(const k of path.split('.'))x=x?.[k];return op==='>='?x>=val:op==='<='?x<=val:op==='=='?x===val:op==='!='?x!==val:false;});return `<button class="topic-choice" data-v3-topic="${esc(id)}:${esc(t.id)}" ${!here||!ok?'disabled':''}><strong>${esc(t.label)}</strong><small>${esc(t.prompt)}</small>${!ok?'<em>条件尚未满足</em>':''}</button>`;}).join('')}</div><div class="dialog-footer"><button data-v3-close>关闭</button></div>`;}
function decoratePeople(stage,s){const h2=stage.querySelector(':scope > h2');if(!h2||!h2.textContent.includes('人物'))return;const cards=[...stage.querySelectorAll('.cards > .card')],ids=Object.keys(D.people);cards.forEach((card,i)=>{const id=ids[i];if(!id||card.querySelector('[data-v3-person]'))return;const meta=N.portrait(id),art=document.createElement('div');art.className='v3-card-glyph stance-'+meta.stance;art.innerHTML=`<span>${esc(meta.glyph)}</span>`;card.prepend(art);const bar=card.querySelector('.buttons');if(bar){const b=document.createElement('button');b.textContent='选择话题';b.dataset.v3Person=id;b.className='v3-topic-open';bar.prepend(b);}});}
function decorateGu(stage){const h2=stage.querySelector(':scope > h2');if(!h2||!h2.textContent.includes('炼蛊'))return;const cards=[...stage.querySelectorAll('.cards > .card')];cards.forEach(card=>{if(card.querySelector('.v3-gu-seal'))return;const name=card.querySelector('h3')?.textContent||'',seal=document.createElement('div');seal.className='v3-gu-seal '+(name.includes('酒虫')?'wine':'moon');seal.textContent=name.includes('酒虫')?'酒':'月';card.prepend(seal);});}
function decorateMap(stage){const h2=stage.querySelector(':scope > h2');if(!h2||!h2.textContent.includes('青茅山'))return;[...stage.querySelectorAll('.map > .card')].forEach((card,i)=>{if(card.querySelector('.v3-place-seal'))return;const id=Object.keys(D.locations)[i],v=N.scene(id),seal=document.createElement('div');seal.className='v3-place-seal tone-'+v.tone;seal.textContent=v.glyph;card.prepend(seal);});}
function injectGraphButton(){const nav=document.querySelector('.tabbar');if(!nav||nav.querySelector('[data-v3-graph]'))return;const b=document.createElement('button');b.textContent='因果图';b.dataset.v3Graph='1';b.className='v3-graph-button';nav.appendChild(b);}
function enhance(){const s=state(),stage=document.querySelector('.stage');injectGraphButton();if(!s||!stage||stage.dataset.v3==='1')return;stage.dataset.v3='1';decoratePeople(stage,s);decorateGu(stage);decorateMap(stage);const story=stage.querySelector('.story-box');if(s.pending&&story){stage.classList.add('legacy-vn');stage.insertAdjacentHTML('afterbegin',scene(s,focal(s)));story.classList.add('v3-dialogue');const e=D.events.find(x=>x.id===s.pending.id),p=focal(s),speaker=document.createElement('div');speaker.className='v3-speaker';speaker.textContent=p?N.portrait(p).role:(e?.title||'青茅山');story.prepend(speaker);return;}if(s.combat&&story){stage.classList.add('legacy-vn','legacy-combat');stage.insertAdjacentHTML('afterbegin',scene(s));story.classList.add('v3-dialogue');return;}const locTitle=stage.querySelector('.location-title');if(locTitle){const v=N.scene(s.location),hero=document.createElement('section');hero.className='v3-location-hero tone-'+v.tone;hero.innerHTML=`<div class="v3-landscape"><div class="mountains far"></div><div class="mountains near"></div><div class="bamboo-layer"></div><span>${esc(v.glyph)}</span></div><div><div class="eyebrow">${esc(v.kicker)}</div><h2>${esc(v.title)}</h2><p>${esc(v.caption)}</p></div>`;locTitle.before(hero);}}
let scheduled=false;const observer=new MutationObserver(()=>{if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;enhance();});});observer.observe(app,{childList:true,subtree:true});
document.addEventListener('click',event=>{const graph=event.target.closest('[data-v3-graph]');if(graph){const s=state();if(!s)return showNotice('先开始一局游戏。');dialog.innerHTML=graphHTML(s);dialog.showModal();return;}const person=event.target.closest('[data-v3-person]');if(person){const s=state();if(!s)return;dialog.innerHTML=topicHTML(s,person.dataset.v3Person);dialog.showModal();return;}const topic=event.target.closest('[data-v3-topic]');if(topic){const [id,tid]=topic.dataset.v3Topic.split(':'),t=N.topicsFor(id).find(x=>x.id===tid);dialog.close();const stage=document.querySelector('.stage'),cards=[...stage.querySelectorAll('.cards > .card')],index=Object.keys(D.people).indexOf(id),chat=cards[index]?.querySelector('button[data-cmd]');if(chat){chat.click();showNotice(`${D.people[id].name} · ${t?.label||'交谈'}：${t?.prompt||''}`);}return;}if(event.target.closest('[data-v3-close]')){dialog.close();return;}if(event.target.closest('.tabbar button:not([data-v3-graph])'))setTimeout(enhance,0);});
enhance();
})();
